<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 23-11-2015 17:11:06 
* Descripcion : formEditErrorBD.phtml
* ---------------------------------------
*/

/*prefijo: ERRBD debe ser alias en tabla men_menuprincipal*/
$eliminar = Session::getPermiso('ERRBDDE');

$data = errorBDController::findErrorBD();

$fecha1 = new DateTime($data['fecha']);                               
$fecha = $fecha1->format('d/m/Y h:i A');      

$buscar=array(chr(13).chr(10), "\r\n", "\n", "\r");
$reemplazar=array(" ", " ", " ", " ");  
$error = str_ireplace($buscar,$reemplazar,$data['error']);       

$id = Aes::en($data['id_error']);

?>
<form id="<?php echo ERRBD; ?>formEditErrorBD" name="<?php echo ERRBD; ?>formEditErrorBD" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo ERRBD_02 ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo ERRBD_03; ?></label>
                        <div class="col col-10">
                            <label class="textarea">
                                <textarea readonly id="<?php echo ERRBD; ?>txt_error" name="<?php echo ERRBD; ?>txt_error" style="height:100px;" ><?php echo $error;?></textarea>                                
                            </label>
                        </div>                       
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo ERRBD_04; ?></label>
                        <div class="col col-10">
                            <label class="textarea">
                                <textarea readonly id="<?php echo ERRBD; ?>txt_descripcion" name="<?php echo ERRBD; ?>txt_descripcion" style="height:100px;" ><?php echo $data['descripcion'];?></textarea>                                
                            </label>
                        </div>                       
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo ERRBD_05; ?></label>
                        <div class="col col-10">
                            <label class="textarea">
                                <textarea readonly id="<?php echo ERRBD; ?>txt_query" name="<?php echo ERRBD; ?>txt_query" style="height:100px;" ><?php  echo $data['query'];?></textarea>                                
                            </label>
                        </div>                       
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo ERRBD_06; ?></label>
                        <div class="col col-10">
                            <label class="textarea">
                                <textarea readonly id="<?php echo ERRBD; ?>txt_param" name="<?php echo ERRBD; ?>txt_param" style="height:30px;" ><?php echo $data['parametros'];?></textarea>                                
                            </label>
                        </div>                       
                    </div>
                </section>
                 <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo ERRBD_07; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input readonly type="text" id="<?php echo ERRBD; ?>txt_ip" name="<?php echo ERRBD; ?>txt_ip" value="<?php echo $data['ip'];?>" >
                            </label>
                        </div>                       
                    </div>
                </section>
                 <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo ERRBD_08; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input readonly type="text" id="<?php echo ERRBD; ?>txt_fecha" name="<?php echo ERRBD; ?>txt_fecha" value="<?php echo $fecha?>" >
                            </label>
                        </div>                       
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>   
                <?php if($eliminar["permiso"]):?>
                <button id="<?php echo ERRBD; ?>btnEdErrorBD" type="submit" class="<?php echo $eliminar["theme"]; ?> padding-5">
                    <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo LABEL_ELIMINAR; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$eliminar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo ERRBD; ?>formEditErrorBD");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo ERRBD; ?>formEditErrorBD").validate({
    rules : {
        <?php echo ERRBD; ?>txt_error : {
            required : true        
        }
    },
  
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        errorBD.postDeleteErrorBD("#<?php echo ERRBD; ?>btnEdErrorBD","<?php echo $id; ?>");
    }   
});
</script>