<?php
$editar = Session::getPermiso('CLADMACT');
?>
<form id="<?php echo CLADM; ?>indexClaveAdm" name="<?php echo CLADM; ?>indexClaveAdm" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 30%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php  echo CLADM_1; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLAV_2; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="password" id="<?php echo CLADM; ?>txt_claveAdm" name="<?php echo CLADM; ?>txt_claveAdm" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo CLADM_2; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                 <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLAV_4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="password" id="<?php echo CLADM; ?>txt_clave2" name="<?php echo CLADM; ?>txt_clave2" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo CLAV_4M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if ($editar['permiso']): ?>
                <button id="<?php echo CLADM; ?>btnEClav" type="submit" class="btn txt-color-white bg-color-blueDark">
                        <i class="fa fa-save"></i> <?php echo $editar['accion']; ?>
                    </button>
                <?php endif; ?>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$editar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo CLADM; ?>indexClaveAdm');
    </script>
<?php endif; ?>
<script>
    $('#<?php echo CLADM; ?>indexClaveAdm').validate({
        rules: {
            <?php echo CLADM; ?>txt_claveAdm: {
                required: true,
                minlength: 3
            },
            <?php echo CLADM; ?>txt_clave2: {
                required: true, 
                equalTo: <?php echo CLADM; ?>txt_claveAdm
            }      
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function() {
            claveAdm.postCambiarClave();
        }
    });
    /*para hacer evento invisible*/
simpleScript.removeAttr.click({
    container: '#<?php echo CLADM; ?>indexClaveAdm',
    typeElement: 'button'
});
</script>