<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 23-11-2015 17:11:06 
* Descripcion : indexErrorBD.phtml
* ---------------------------------------
*/
$consultar    = Session::getPermiso("ERRBDCC");
$eliminar = Session::getPermiso('ERRBDDE');
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>ERRBD,
        "title"=>ERRBD_01,
        'actions' => array(               
                array(
                    'id' => ERRBD . 'gridErrorBD_btnRecarga',                    
                    'permiso'=> 'ERRBDREC',
                    'click' => 'errorBD.getGridErrorBD();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">                 
            </div>
        </div>

    </div>    
    <table id="<?php echo ERRBD; ?>gridErrorBD" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
        
 <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($consultar["permiso"]): ?>
                        <button type="button" class="<?php echo $consultar["theme"]; ?> margin-top-5" title="<?php echo $consultar["accion"]; ?>" ><i class="<?php echo $consultar["icono"];?>"></i>  <?php echo $consultar["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                    <?php if($eliminar["permiso"]): ?>
                        <button type="button" class="<?php echo $eliminar["theme"]; ?> margin-top-5" title="<?php echo $eliminar["accion"]; ?>" ><i class="<?php echo $eliminar["icono"];?>"></i>  <?php echo $eliminar["accion"]; ?> </button>                    
                    <?php endif;?>      
                </div>
            </div>

        </section>
    </div>

<?php echo Functions::widgetClose(); ?>