<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 21-08-2014 07:08:16 
* Descripcion : indexCliente.phtml
* ---------------------------------------
*/
$grabar = Session::getPermiso("CAJACGN");

$data = cajaCierreController::findCaja();
    
$moneda = $data['moneda'];
$sigla = $data['sigla'];

echo Functions::widgetOpen(array(
        "id"=>CAJAC,
        "title"=>CAJAC_2.' - N° Caja: '.$data['id_caja'],
        'overflow'=> 'none'
    )); 
?>
  
<form id="<?php echo CAJAC; ?>formNewCierre" name="<?php echo CAJAC; ?>formNewCierre" onsubmit="return false;">
        <div class="pull-left padding-10 col-xs-12 col-lg-6" style="border-right: 1px solid #ccc">
            <div class="modal-body smart-form" >
                <section>
                        <div class="row">                                                                                                                                                                
                             <label class="label col-lg-2"><?php echo CAJAC_8; ?></label>
                            <div class="col-lg-10">                                
                                <label class="input"> 
                                    <i class="icon-append fa fa-industry"></i>                                
                                    <input style="background: #eee;" type="text" id="<?php echo CAJAC; ?>txt_sucursal" name="<?php echo CAJAC; ?>txt_sucursal" value="<?php echo $data['sucursal'];  ?>" readonly>
                             </label>
                            </div>                            
                            <div class="col-lg-12"><br><hr></div>   
                        </div>
                </section>
                <section>
                    <div class="row"> 
                        <div class="col-xs-12 col-lg-6"><h1><?php echo CAJAC_6.': '.$moneda; ?></h1></div>                            
                        <div class="col-xs-12 col-lg-6"><h2><?php echo CAJAC_9.': '.Functions::cambiaf_a_normal($data['fecha_caja']); ?></h2></div>                                                        
                    </div>
                </section>
                <section>
                        <div class="row">                                                                                                                                                                 
                            <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_10; ?></label>
                            <div class="col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_tv" name="<?php echo CAJAC; ?>txt_tv" value="<?php echo number_format($data['total_ventas'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_10M; ?></b>
                             </label>
                            </div>                 
                            <label class="label col-xs-12 col-lg-2">&nbsp;&nbsp;<?php echo CAJAC_12; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_saldoVentas" name="<?php echo CAJAC; ?>txt_saldoVentas" value="<?php echo number_format($data['saldo_ventas'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_12M; ?></b>
                             </label>
                            </div>                                                          
                            <div class="col-lg-12"><br><hr></div>   
                        </div>
                </section>  
                
                <section>
                        <div class="row">                                                                                                                                                                 
                            <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_11; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_cc" name="<?php echo CAJAC; ?>txt_cc" value="<?php echo number_format($data['total_acuenta'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_11M; ?></b>
                             </label>
                            </div>                             
                            <label class="label col-xs-12 col-lg-2">&nbsp;&nbsp;<?php echo CAJAC_29; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_otros" name="<?php echo CAJAC; ?>txt_otros" value="<?php echo number_format($data['total_otros'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_29M; ?></b>
                                    
                             </label>
                            </div>  
                        </div>
                </section>  
                <section>
                        <div class="row">                                                                                                                                                                 
                            <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_32; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right; font-weight: bold;" type="text" id="<?php echo CAJAC; ?>txt_tpagos" name="<?php echo CAJAC; ?>txt_tpagos" value="<?php echo number_format($data['total_acuenta']+$data['total_otros'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_32M; ?></b>
                             </label>
                            </div>                                                          
                            <label class="label col-xs-12 col-lg-2">&nbsp;&nbsp;<?php echo CAJAC_13; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_ingresoDirecto" name="<?php echo CAJAC; ?>txt_ingresoDirecto" value="<?php echo number_format($data['total_ingresoDirecto'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_13M; ?></b>
                             </label>
                            </div>
                            <div class="col-lg-12"><br><hr></div> 
                        </div>                    
                </section> 
                <section>
                        <div class="row">                                                                                                                                                                 
                            <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_33; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_tefectivo" name="<?php echo CAJAC; ?>txt_tefectivo" value="<?php echo number_format($data['total_acuenta']+$data['total_ingresoDirecto'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_33M; ?></b>
                             </label>
                            </div>                                                          
                            <label class="label col-xs-12 col-lg-2">&nbsp;&nbsp;<?php echo CAJAC_17; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right" type="text" id="<?php echo CAJAC; ?>txt_inicial" name="<?php echo CAJAC; ?>txt_inicial" value="<?php echo number_format($data['monto_inicial'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_17M; ?></b>
                             </label>
                            </div>
                            <div class="col-lg-12"><br><hr></div>   
                        </div>                                            
                </section> 
                <section>
                        <div class="row">                                                                                                                                                                 
                            <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_14; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right; font-weight: bold" type="text" id="<?php echo CAJAC; ?>txt_ingresos" name="<?php echo CAJAC; ?>txt_ingresos" value="<?php echo number_format($data['total_ingresos'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_14M; ?></b>
                             </label>
                            </div>                              
                            <label class="label col-xs-12 col-lg-2">&nbsp;&nbsp;<?php echo CAJAC_15; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right; font-weight: bold" type="text" id="<?php echo CAJAC; ?>txt_egresos" name="<?php echo CAJAC; ?>txt_egresos" value="<?php echo number_format($data['total_egresos'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_15M; ?></b>
                             </label>
                            </div>  
                        </div>                        
                </section> 
                
                <section>
                        <div class="row">                                                                                                                                                                 
                            <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_16; ?></label>
                            <div class="col-xs-12 col-lg-4">
                                <label class="input"> 
                                    <i class="icon-append fa fa-money"></i>                                
                                    <input style="background: #eee;text-align: right; font-weight: bold" type="text" id="<?php echo CAJAC; ?>txt_saldoCaja" name="<?php echo CAJAC; ?>txt_saldoCaja" value="<?php echo number_format($data['saldo'],2);  ?>" readonly>
                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_16M; ?></b>
                                </label>
                            </div>                             
                        </div>
                </section> 
                <section>
                        <div class="row"> 
                            <div class="col-lg-12">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo CAJAC_7; ?></div>            
                            </div>                              
                            <div class="col-lg-12">
                                <table id="<?php echo CAJAC; ?>gridMetodoPago" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">
                                <thead>
                                    <th style="width:40%"><?php echo CAJAC_19?></th>
                                    <th style="width:60%; text-align: right;"><?php echo CAJAC_20?></th>                                  
                                </thead>
                                <tbody>
                                    <?php 
                                        $dataMP = Obj::run()->cajaCierreController->findMetodoPagoAll(); 
                                        $rows = sizeof($dataMP);
                                        $totalCajaMP = 0;
                                        foreach ($dataMP as $r):                            
                                            $idd = AesCtr::en($r['id_metodopago']);  
                                            $idx = $r['id_metodopago'];
                                            $css= 'background: #eee;';
                                            $readonly = 'readonly';  
                                            $totalCajaMP += $r['ingresos'];
                                            ?>  
                                        <tr id="<?php echo CAJAC; ?>tr_mp_<?php echo ($idx); ?>" >
                                            <td style="width: 50%">
                                                <label class="input">
                                                    <input type="hidden" id="<?php echo CAJAC; ?>hhddIdTipoMP" name="<?php echo CAJAC; ?>hhddIdTipoMP[]" value="<?php echo $idd; ?>" >
                                                    <input style="background: #eee; text-align: right;" type="text" id="<?php echo CAJAC.$idx; ?>txt_texto" name="<?php echo CAJAC; ?>txt_texto[]" value="<?php echo $r['descripcion'];?>" disabled data-index="<?php echo $idx; ?>" >
                                                </label>                                
                                            </td>                                                                                                                                                                         
                                            <td class="right">                                                
                                                <label class="input">
                                                    <i class="icon-append <?php echo $r['icono'];?>"></i>
                                                    <input style="text-align: right; font-weight: bold; <?php echo $css; ?>" type="text" id="<?php echo CAJAC.$idx; ?>txt_importe" name="<?php echo CAJAC; ?>txt_importe[]" value="<?php echo number_format($r['ingresos'],2); ?>" data-index="<?php echo $idx; ?>" <?php echo $readonly; ?> >                                                    
                                                </label>
                                            </td>                                                                                                                                                                      
                                        </tr>                                    
                                     <?php endforeach; ?> 
                                       </tbody>
                                    </table> 
                                     <table id="<?php echo CAJAC; ?>gridMetodoPagoTotal" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">   
                                         <tbody>
                                             <tr id="<?php echo CAJAC; ?>tr_mp_total" >
                                                 <td  style="width: 50%; text-align: right;"><label class="input" style="font-weight: bold;"><?php echo CAJAC_31;?></label></td>                                                                                                                                                                         
                                             <td class="right">                                                
                                                <label class="input">
                                                    <i class="icon-append fa fa-check-square"></i>
                                                    <input class="txt-color-red" style="text-align: right; font-weight: bold; <?php echo $css; ?>" type="text" id="<?php echo CAJAC; ?>txt_importeTotalCaja" name="<?php echo CAJAC; ?>txt_importeTotalCaja" value="<?php echo number_format($totalCajaMP,2); ?>" <?php echo $readonly; ?> >                                                    
                                                </label>
                                            </td>                                                                                                                                                                      
                                        </tr>
                                </tbody>
                                </table>                                
                            </div>                                                                                                               
                        </div>
                    </section>                                                                                             
            </div>
        </div>
        <div  class="pull-right padding-10 col-xs-12 col-lg-6" >
            <div class="modal-body smart-form" >                     
                    <section>
                        <div class="row"> 
                            <div class="alert alert-success"><i class="fa fa-info-circle"></i> <?php echo CAJAC_3M; ?></div>            
                        </div>
                    </section>
                    <section>
                        <div class="row">
                            <div class="col-xs-12 col-lg-6">
                                 <table id="<?php echo CAJAC; ?>gridBillete" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">
                                <thead>
                                    <th style="width:36%"><?php echo CAJAC_4?></th>
                                    <th style="width:32%"><?php echo CAJAC_18?></th>                                 
                                    <th style="width:32%"><?php echo CAJAC_21?></th>
                                </thead>
                                <tbody>
                                        <?php 
                                        $dataB = Obj::run()->cajaCierreController->findDenominacionAll($data['id_moneda'],'B'); 
                                        $rows = sizeof($dataB);
                                        foreach ($dataB as $r):                            
                                            $idd = Aes::en($r['id_denominacion']); 
                                            $idx = $r['id_denominacion'];
                                            $cantidad = $sigla.' '.number_format($r['cantidad'],2);                              
                                            ?>
                                        <tr id="<?php echo CAJAC; ?>tr_moneda_<?php echo ($idx); ?>" >
                                            <td>
                                               <input type="hidden" id="<?php echo CAJAC; ?>hhddIdDenominacion" name="<?php echo CAJAC; ?>hhddIdDenominacion[]" value="<?php echo $idd; ?>" >
                                                <label class="input">
                                                    <input style="background: #eee; text-align: right;" type="text" id="<?php echo CAJAC.$idx; ?>txt_denominacion" name="<?php echo CAJAC; ?>txt_denominacion[]" value="<?php echo $cantidad;?>" disabled data-index="<?php echo $idx; ?>" data-cantidad="<?php echo $r['cantidad'];?>">
                                                </label>                                
                                            </td>                                                                                                                                                                         
                                            <td class="right">
                                                <label class="input">
                                                    <input style="text-align: right" type="text" id="<?php echo CAJAC.$idx; ?>txt_cantidad" name="<?php echo CAJAC; ?>txt_cantidad[]" value="0" data-index="<?php echo $idx; ?>">
                                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_4M; ?></b>
                                                </label>
                                            </td>                                                                                                                                                                      
                                            <td class="right">0.00</td>                                          
                                        </tr>       
                                     <?php endforeach; ?> 
                                </tbody>
                                </table>
                            </div>
                            
                            <div class="col-xs-12 col-lg-6">
                                <table id="<?php echo CAJAC; ?>gridMoneda" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">
                                <thead>
                                    <th style="width:36%"><?php echo CAJAC_5?></th>
                                    <th style="width:32%"><?php echo CAJAC_18?></th>                                 
                                    <th style="width:32%"><?php echo CAJAC_21?></th>                                 
                                </thead>
                                <tbody>
                                        <?php 
                                        $dataB = Obj::run()->cajaCierreController->findDenominacionAll($data['id_moneda'],'M'); 
                                        $rows = sizeof($dataB);
                                        foreach ($dataB as $r):                            
                                            $idd = AesCtr::en($r['id_denominacion']); 
                                            $idx = $r['id_denominacion'];
                                            $cantidad = $sigla.' '.number_format($r['cantidad'],2);                              
                                            ?>
                                        <tr id="<?php echo CAJAC; ?>tr_moneda_<?php echo ($idx); ?>" >
                                            <td>
                                               <input type="hidden" id="<?php echo CAJAC; ?>hhddIdDenominacion" name="<?php echo CAJAC; ?>hhddIdDenominacion[]" value="<?php echo $idd; ?>" >
                                                <label class="input">
                                                    <input style="background: #eee; text-align: right;" type="text" id="<?php echo CAJAC.$idx; ?>txt_denominacion" name="<?php echo CAJAC; ?>txt_denominacion[]" value="<?php echo $cantidad;?>" disabled data-index="<?php echo $idx; ?>" data-cantidad="<?php echo $r['cantidad'];?>">
                                                </label>                                
                                            </td>                                                                                                                                                                         
                                            <td class="right">
                                                <label class="input">
                                                    <input style="text-align: right" type="text" id="<?php echo CAJAC.$idx; ?>txt_cantidad" name="<?php echo CAJAC; ?>txt_cantidad[]" value="0" data-index="<?php echo $idx; ?>">
                                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_5M; ?></b>
                                                </label>
                                            </td>
                                            <td class="right">0.00</td>                                          
                                        </tr>       
                                     <?php endforeach; ?> 
                                </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </section>
                    <section>
                            <div class="row">    
                                 <div class="col-lg-12">
                                    <div class="alert alert-warning"><i class="fa fa-info-circle"></i> <?php echo CAJAC_26; ?></div>            
                                 </div>
                                <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_30; ?></label>
                                <div class="col-xs-12 col-lg-4">
                                    <label class="input"> 
                                        <i class="icon-append fa fa-money"></i>                                
                                        <input style="background: #eee;text-align: right; font-weight: bold" type="text" id="<?php echo CAJAC; ?>txt_totalEfectivoCaja" name="<?php echo CAJAC; ?>txt_totalEfectivoCaja" value="<?php echo number_format($data['saldo'],2);  ?>" readonly>
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_30M; ?></b>
                                    </label>
                                </div>
                            </div>
                    </section>
                    <section>
                            <div class="row">   
                                <label class="label col-xs-12 col-lg-2"><?php echo CAJAC_24; ?></label>
                                <div class="col-xs-12 col-lg-4">
                                    <label class="input"> 
                                        <i class="icon-append fa fa-money"></i>                                
                                        <input style="background: #eee;text-align: right; font-weight: bold" type="text" id="<?php echo CAJAC; ?>txt_totalCaja" name="<?php echo CAJAC; ?>txt_totalCaja" value="0.00" readonly>
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_24M; ?></b>
                                    </label>
                                </div>
                                <label class="label col-xs-12 col-lg-2">&nbsp;&nbsp;<?php echo CAJAC_25; ?></label>
                                <div class="col-xs-12 col-lg-4">
                                    <label class="input"> 
                                        <i class="icon-append fa fa-money"></i>                                
                                        <input style="background: #eee;text-align: right; font-weight: bold" type="text" id="<?php echo CAJAC; ?>txt_diferencia" name="<?php echo CAJAC; ?>txt_diferencia" value="0.00" readonly>
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAC_25M; ?></b>
                                    </label>
                                </div>
                            </div>
                    </section>
                    <section>
                        <div class="row">
                            <label class="label col-lg-12"><?php echo LABEL_OBS; ?></label>
                            <div class="col-lg-12">
                                <div class="textarea">
                                    <textarea style="height: 140px;" class="form-control" id="<?php echo CAJAC; ?>txt_observacion" name="<?php echo CAJAC; ?>txt_observacion"></textarea>
                                </div>
                            </div>
                        </div>
                    </section>     
                <section>
                    <div class="row">
                        <div class="col-xs-12">
                             <?php if($grabar["permiso"]):?>
                            <hr/>
                            <h4 class="text-center padding-10">
                                <button type="submit" id="<?php echo CAJAC; ?>btnGrCierre" class="btn btn-success btn-large padding-10" onclick="cajaCierre.postGenerarCierre();">    
                                    <i class="fa fa-plus-circle fa-lg"></i>
                                    <?php echo CAJAC_3; ?>
                                </button>
                            </h4>
                             <?php endif; ?>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </form>
    <div class="clearfix"></div>
   
<?php echo Functions::widgetClose(); ?>
<script>
    cajaCierreScript.calculoTotalFilaUp();  
</script>
 