<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 22-11-2014 20:11:18 
* Descripcion : formEditVegresos.phtml
* ---------------------------------------
*/

/*prefijo: VEGRE debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("VEGREACT");
    
$data = vegresosController::findVegresos();

?>
<form id="<?php echo VEGRE; ?>formEditVegresos" name="<?php echo VEGRE; ?>formEditVegresos" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VEGRE_3; ?></h4>
            </div>
            <div class="modal-body smart-form">                
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VEGRE_5; ?></label>
                        <div class="col col-10">
                            <div class="textarea">
                                <textarea class="form-control" id="<?php echo VEGRE; ?>txt_descripcion" name="<?php echo VEGRE; ?>txt_descripcion"><?php echo $data['descripcion']; ?></textarea>
                                 <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VEGRE_5M; ?></b>
                            </div>
                        </div>
                    </div>
                </section>                 
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo VEGRE; ?>btnEdVegresos" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VEGRE; ?>formEditVegresos");
</script>
<?php endif; ?>
<script>
    simpleScript.setEvent.date({
        element: '#<?php echo VEGRE; ?>txt_fecha' 
    });
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo VEGRE; ?>formEditVegresos").validate({
    rules : {
      <?php echo VEGRE; ?>txt_descripcion : {
            required : true,
            minlength: 3
        }     
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        vegresos.postEditVegresos();
    }   
});
</script>