<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 11-04-2016 23:04:55 
* Descripcion : formMigrarCotizacion.phtml
* ---------------------------------------
*/

/*prefijo: VCOTI debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("VCOTIMIGR");   
$idd =Aes::de(Formulario::getParam("_idCotizacion")); 
?>
<form id="<?php echo VCOTI; ?>formMigrarCotizacion" name="<?php echo VCOTI; ?>formMigrarCotizacion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VCOTI_11.' - N°: '.$idd; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
               <section >
                        <div class="row">                              
                            <label class="label col col-xs-2"><?php echo VCOTI_12; ?>  </label>
                            <div class="col col-xs-10">
                                  <label class="select" > 
                                     <?php
                                         $dataEmpleados = generarCotizacionController::getEmpleadosAll();
                                             echo Functions::selectHtml(array(
                                                 'data'=>$dataEmpleados,
                                                 'atributes'=>array(
                                                     'id'=>VCOTI.'lst_usuario',
                                                     'name'=>VCOTI.'lst_usuario'                                                   
                                                 ),  
                                                 'etiqueta'=>'nombrecompleto',
                                                 'value'=>'id_usuario',
                                                 'defaultEtiqueta'=>$dataEmpleados,
                                                 'txtSelect'=>false,
                                                 'encript'=> true
                                         ));
                                  ?>                                  
                                  </label>                                                                                           
                              </div>
                        </div>
                  </section> 
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo VCOTI; ?>btnEdMigrar" type="submit" class="padding-5 <?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VCOTI; ?>formMigrarCotizacion");
</script>
<?php endif; ?>
<script>
    simpleScript.chosen({'id':'#<?php echo VCOTI; ?>lst_usuario'});  
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo VCOTI; ?>formMigrarCotizacion").validate({
    rules : {
        <?php echo VCOTI; ?>lst_usuario : {
            required : true            
        }
    },   
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        vGenerarCotizacion.postMigrarCotizacion();
    }   
});
</script>