<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-12-2014 21:12:27 
* Descripcion : formNewCajaApertura.phtml
* ---------------------------------------
*/

/*prefijo: CAJAA debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("CAJAAGR");

$fecha = Functions::formato_fecha(date('Y-m-d h:i:s'));

if( Session::get('sys_visible') == 'S'){
    $idSucursal = 1; // Administrador por defecto 1. Ya al seleccionar el combo se mostrara los demas cajas x sucursal.
    $css = ''; 
    $disabled = '';
}else{
    $idSucursal = Session::get('sys_idSucursal'); // Sucursal configurada desde usuarios para el cajero.
    $css = 'background: #eee; '; 
    $disabled = 'readonly';
}
$montoUltimo = cajaAperturaController::getUltimoSaldo($idSucursal);

?>
<form id="<?php echo CAJAA; ?>formNewCajaApertura" name="<?php echo CAJAA; ?>formNewCajaApertura" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CAJAA_4.$fecha ?></h4>
            </div>
            <div class="modal-body smart-form">
                <?php  if( Session::get('sys_visible') == 'S' ): ?>                                    
                <section >
                    <div class="row">                              
                        <label class="label col col-3"><?php echo VGEVE_15; ?>  </label>
                        <div class="col col-8">
                              <label class="select"> 
                                 <?php
                                     $dataSucursal = vSucursalController::getSucursalAll();
                                         echo Functions::selectHtml(array(
                                             'data'=>$dataSucursal,
                                             'atributes'=>array(
                                                 'id'=>CAJAA.'lst_sucursal',
                                                 'name'=>CAJAA.'lst_sucursal',
                                                  'onchange'=>'cajaApertura.getCajaSaldo({
                                                            idSucursal: $(\'#'.CAJAA.'lst_sucursal\').val(),
                                                            idElement: \'#'.CAJAA.'txt_inicio\'
                                                        });'
                                             ),  
                                             'etiqueta'=>'descripcion',
                                             'value'=>'id',
                                             'defaultEtiqueta'=>'1',
                                             'txtSelect'=>false,
                                             'encript' => true
                                     ));
                                ?><i></i>                                  
                              </label>                                                                                           
                          </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CAJAA_5; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-calendar-o "></i>
                                <input type="text" id="<?php echo CAJAA; ?>txt_fecha" name="<?php echo CAJAA; ?>txt_fecha" value="<?php echo date("d/m/Y"); ?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CAJAA_5M; ?></b>
                            </label>
                        </div> 
                         </div>
                </section>    
               <?php endif; ?>
               <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CAJAA_3; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input <?php echo $disabled; ?> style="text-align: right; <?php echo $css; ?>" type="text" id="<?php echo CAJAA; ?>txt_inicio" name="<?php echo CAJAA; ?>txt_inicio" value="<?php echo number_format($montoUltimo['saldo'],2);?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-money txt-color-teal"></i> <?php echo CAJAA_3M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo CAJAA; ?>btnGrCajaApertura" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CAJAA; ?>formNewCajaApertura");
</script>
<?php endif; ?>
<script>
       
    simpleScript.setEvent.date({
      element: '#<?php echo CAJAA; ?>txt_fecha'
    });
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo CAJAA; ?>formNewCajaApertura").validate({
    rules : {
        <?php echo CAJAA; ?>txt_inicio : {
            required : true,
            number: true
        }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        cajaApertura.postNewCajaApertura();
    }   
});
</script>