<?php 
/*prefijo: VGEVE debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso('VMOVEMOD');
$agregar = Session::getPermiso('VMOVEAG');
$buscar = Session::getPermiso('VMOVEBS');

$datac = Obj::run()->generarVentaController->getFindVenta();
$datad = Obj::run()->generarVentaController->getFindVentaD();

echo Functions::widgetOpen(array(
    'id' => VGEVE.'_EDITAR',
    'title' => VGEVE_41.$datac['codigo_impresion'],
    'padding' => true,
    'overflow'=> 'none',
    'wizard' => true
));

$dataCodigo = generarVentaController::getCodigo();
$codigo = $dataCodigo['cod'];

if( Session::get('sys_visible') == 'S' ){
    $idSucursal = 1; // Administrador por defecto 1. Ya al seleccionar el combo se mostrara los demas cajas x sucursal.
}else{
    $idSucursal = Session::get('sys_idSucursal'); // Sucursal configurada desde usuarios para el cajero.
}

if(empty($datac['empresa']) || $datac['empresa'] == '' ){
    $cliente = $datac['cliente'];
}else{
    $cliente = $datac['empresa'].' | '.$datac['cliente'];
}
$igv = parametroController::getParametroOne('IGV');

?>
<form id="<?php echo VMOVE; ?>formEditGenerarVenta" name="<?php echo VMOVE; ?>formEditGenerarVenta" novalidate="novalidate" onsubmit="return false;">
        <div class="modal-body smart-form" >
                    <section>
                        <div class="row">
                                <div class="alert alert-info ">
                                     <i class="fa fa-info-circle"></i> Paso 1: Por favor, ingrese los datos de caja. Tenga en cuenta que ud. generará otra orden.
                                </div>
                        </div>
                    </section>  
                   <section >
                          <div class="row">
                              <label class="label col col-1" for="prepend"><?php echo VRECL_9; ?></label>                                                            
                              <div class="col col-9">
                                  <label class="input"> 
                                      <i class="icon-append fa fa-user"></i>
                                      <input type="hidden" id="<?php echo VGEVE; ?>txt_porcentaje" name="<?php echo VGEVE; ?>txt_porcentaje" value="<?php echo $igv; ?>">
                                      <input type="hidden" id="<?php echo VGEVE; ?>txt_idpersona" name="<?php echo VGEVE; ?>txt_idpersona" value="<?php echo Aes::en($datac['id_persona']);?>">
                                      <input style="background: #eee;" type="text" id="<?php echo VGEVE; ?>txt_cliente" name="<?php echo VGEVE; ?>txt_cliente" readonly="readonly" value="<?php echo $cliente;?>" >
                                      <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo VGEVE_40; ?></b>
                                  </label>
                              </div>
                              <div class="col col-1" >
                                  <?php if ($buscar['permiso']): ?>
                                  <button class="btn txt-color-white bg-color-blueDark" style="padding:5px 10px;" type="button" 
                                                    disabled>
                                                <i class="<?php echo $buscar['icono'];?>"></i> <?php echo $buscar['accion'];?></button>
                                    <?php endif; ?>              
                              </div>                                                              
                          </div>
                    </section>                                                           
                     <?php  if( Session::get('sys_visible') == 'S' ): ?>   
                    <section >
                          <div class="row">                              
                              <label class="label col col-xs-1"><?php echo VGEVE_15; ?>  </label>
                              <div class="col col-xs-11">
                                    <label class="select" > 
                                       <?php
                                           $dataSucursal = vSucursalController::getSucursalAll('S');
                                               echo Functions::selectHtml(array(
                                                   'data'=>$dataSucursal,
                                                   'atributes'=>array(
                                                       'id'=>VGEVE.'lst_sucursal',
                                                       'name'=>VGEVE.'lst_sucursal',  
                                                        'onchange'=>'cajaApertura.getCaja({
                                                            idSucursal: $(\'#'.VGEVE.'lst_sucursal\').val(),
                                                            content: \'#'.VGEVE.'cont-caja\',
                                                            idElement: \''.VGEVE.'lst_caja\',
                                                            nameElement: \''.VGEVE.'lst_caja\'                                                         
                                                        });'
                                                   ),  
                                                   'etiqueta'=>'descripcion',
                                                   'value'=>'id',
                                                   'defaultEtiqueta'=>$idSucursal,
                                                   'txtSelect'=>true,
                                                   'encript'=> true
                                           ));
                                    ?>                                  
                                    </label>                                                                                           
                                </div>
                          </div>
                    </section>
                     <?php endif; ?>
                    <section >
                          <div class="row">
                               <label class="label col col-1"><?php echo VGEVE_7; ?> </label>
                              <div class="col col-4">
                                  <label class="input"> 
                                      <i class="icon-append fa fa-cogs"></i>
                                      <input type="text" id="<?php echo VGEVE; ?>txt_codImpr" name="<?php echo VGEVE; ?>txt_codImpr" maxlength="6" value="<?php echo $codigo;?>">                                      
                                      <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo VGEVE_7M; ?></b>
                                  </label>
                              </div>
                              <label class="label col col-1"><?php echo VGEVE_33; ?>  </label>
                              <div class="col col-6">
                                    <label class="select" id="<?php echo VGEVE; ?>cont-caja"> 
                                       <?php
                                           $dataCaja = cajaAperturaController::getDataCajaAll($idSucursal);
                                               echo Functions::selectHtml(array(
                                                   'data'=>$dataCaja,
                                                   'atributes'=>array(
                                                       'id'=>VGEVE.'lst_caja',
                                                       'name'=>VGEVE.'lst_caja',                                            
                                                   ),  
                                                   'etiqueta'=> 'descripcion',
                                                   'value'=>'id_caja',
                                                   'defaultEtiqueta'=>'',
                                                   'txtSelect'=>false,
                                                   'encript'=>true
                                           ));
                                               ?> <i></i>                                 
                                    </label>                                                                                           
                              </div>
                          </div>
                    </section>              
                    <section>
                        <div class="row"> 
                            <div class="col-lg-12"><hr><br></div>                                                                             
                            <div class="col-lg-12">
                                <div class="alert alert-info"><i class="fa fa-info-circle"></i> Paso 2: Dar clic en el botón para agregar productos o servicios, escriba la descripción(en caso sea servicio) y el precio, el cálculo del importe es automático.</div>            
                            </div> 
                            <div class="clearfix"></div>
                            <label class="control-label col-lg-2" for="prepend">
                                <?php if($agregar['permiso']):?>
                                <button id="<?php echo VGEVE; ?>btnGaddFila" type="button" class="<?php echo $agregar['theme'];?> padding-10" onclick="generarVenta.getFormBuscarProductos(this,'<?php echo VGEVE; ?>' );">
                                    <i class="fa fa-plus-circle"></i> <?php echo BTN_ADD; ?> Producto / Servicio en la tabla
                                </button>
                                <br/><br/>
                                <?php endif; ?>
                            </label>
                            <div class="col-lg-12">
                                <div id="<?php echo VGEVE; ?>GridDetalle" style="padding: 10px">
                                    <div class="tabla" style="min-height: 200px; max-height: auto;">
                                        <table id="<?php echo VGEVE; ?>gridProductos" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">
                                            <thead>
                                                <th style="width:39%"><?php echo VGEVE_9?></th>
                                                <th style="width:9%"><?php echo VGEVE_10?></th>
                                                <th style="width:9%"><?php echo VGEVE_11?></th>
                                                <th style="width:8%"><?php echo VGEVE_12?></th>
                                                <th style="width:8%"><?php echo VGEVE_22?></th>
                                                <th style="width:10%"><?php echo VGEVE_13?></th>
                                                <th style="width:10%"><?php echo VGEVE_14?></th>
                                                <th style="width:1%">...</th>
                                            </thead>
                                            <tbody>
                                       <?php 
                                        $key = 0;
                                        foreach ($datad as $value):
                                            $idProducto = AesCtr::en($value['id_producto']);         
                                            $idx = $idx + 1;
                                            $descripcion = str_replace('\\','',$value['descripcion'] );                                        
                                            $descripcion = htmlspecialchars_decode($descripcion,ENT_QUOTES);
                                    ?>
                                    <script>generarVentaScript.setIndex();</script>
                                        <tr id="<?php echo VGEVE; ?>tr_<?php echo ($idx); ?>" >
                                            <td>                                                
                                                <input type="hidden" id="<?php echo VGEVE.$idx; ?>hhddIdProducto" name="<?php echo VGEVE; ?>hhddIdProducto[]" value="<?php echo $idProducto; ?>">
                                                <label class="textarea">
                                               <?php if( $value['id_producto'] == 201600000001 ): ?>                                                                                                  
                                                    <textarea class="editable" style="height:120px; resize: vertical;" autocomplete="on" id="<?php echo VGEVE.$idx; ?>txt_descripcion" name="<?php echo VGEVE; ?>txt_descripcion[]" ><?php echo $descripcion; ?></textarea>
                                                <?php else:?>
                                                     <textarea style="background:#EFEFEF;" autocomplete="on" disabled id="<?php echo VGEVE.$idx; ?>txt_descripcion" name="<?php echo VGEVE; ?>txt_descripcion[]" ><?php echo $value['producto'] ?></textarea>
                                                <?php endif; ?>
                                             </label>                                                                                                
                                            </td>
                                            <td ><?php echo $value['sigla']; ?></td>
                                            <td>
                                                <label class="input">
                                                    <input type="text" id="<?php echo VGEVE.$idx; ?>txt_cantidad1" name="<?php echo VGEVE; ?>txt_cantidad1[]" value="<?php echo number_format($value['cantidad_1'],0); ?>"  style="text-align:right" data-index="<?php echo $idx; ?>">
                                                </label>                                
                                            </td>
                                            <td >
                                                <label class="input">
                                                <?php if($value['cantidad_multiple'] == 0): ?>
                                                    <input readonly type="text" style="background:#EFEFEF;text-align:right;"  id="<?php echo VGEVE.$idx; ?>txt_cantidad2" name="<?php echo VGEVE; ?>txt_cantidad2[]" value="<?php echo number_format($value['cantidad_2'],0); ?>" data-index="<?php echo $idx; ?>">   
                                                <?php else: ?>
                                                    <input type="text" id="<?php echo VGEVE.$idx; ?>txt_cantidad2" name="<?php echo VGEVE; ?>txt_cantidad2[]" value="<?php echo number_format($value['cantidad_2'],0); ?>" style="text-align:right" data-index="<?php echo $idx; ?>">
                                                <?php endif; ?>  
                                                </label> 
                                            </td>                                            
                                            <td class="right">
                                                <?php echo number_format($value['cantidad_real'],2); ?>
                                            </td>                                                                                        
                                            <td class="right">
                                                <label class="input"><input type="text" id="<?php echo VGEVE.$idx; ?>txt_precio" name="<?php echo VGEVE; ?>txt_precio[]" value="<?php echo number_format($value['precio'],2); ?>" data-value="<?php echo number_format($value['precio'],2); ?>" data-index="<?php echo $idx; ?>" style="text-align:right" type="text"></label>
                                            </td>                                                                                                                                                                      
                                            <td class="right"><?php echo number_format($value['importe'],2); ?></td>
                                            <td>
                                                <button type="button" class="btn btn-danger btn-xs" onclick="generarVentaScript.removeItem('<?php echo $idx; ?>');"><i class="fa fa-trash-o"></i>
                                                </button>
                                            </td>                                            
                                        </tr>    
                                    <?php endforeach; ?>      
                                        
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="form-group" style="margin-top:5px">
                                        <div class="col-md-2 pull-right">
                                            <div class="input">
                                                <input class="form-control right" type="text" id="<?php echo VGEVE; ?>txt_total" name="<?php echo VGEVE; ?>txt_total" readonly>
                                            </div>
                                        </div>
                                        <label class="control-label col-md-2 pull-right" for="prepend"><?php echo LABEL_T; ?></label>
                                    </div>
                                </div>
                            </div>                            
                        </div>                        
                    </section>
            
                    <section>
                        <div class="row">
                                <div class="alert alert-info ">
                                     <i class="fa fa-info-circle"></i> Paso 3: Por favor, ingrese los datos del pago de la venta
                                </div>
                        </div>
                    </section>
            <section>    
                             <div class="row">
                                <label class="label col col-2"><?php echo VPROD7; ?> </label>
                                <div class="col col-2">
                                      <label class="select"> 
                                            <?php                               
                                               $igv = Array (
                                                        Array ( 'id' => 'S', 'descripcion' => LABEL_S ),
                                                        Array ( 'id' => 'N', 'descripcion' => LABEL_N )
                                                );     
                                                echo Functions::selectHtml(array(
                                                    'data'=>$igv,
                                                    'atributes'=>array(
                                                        'id'=>VGEVE.'lst_igv',
                                                        'name'=>VGEVE.'lst_igv',
                                                        'onchange'=>'generarVentaScript.inclIGV();'
                                                    ),
                                                    'etiqueta'=>'descripcion',
                                                    'value'=>'id',
                                                    'defaultEtiqueta'=>"S",
                                                    'txtSelect'=>false
                                                ));
                                            ?><i></i>
                                        </label> 
                                    </div>                                                
                              </div>
                        </section>    
                        <section>    
                             <div class="row">
                                  <label class="label col col-2"><?php echo VGEVE_28; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-money"></i>
                                            <input style="text-align: right; background: #eee;" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_venta" name="<?php echo VGEVE; ?>txt_venta" readonly >
                                        </label>
                                  </div> 
                                  <label class="label col col-2"><?php echo VGEVE_29; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-money"></i>
                                            <input style="text-align: right;background: #eee;" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_impuesto" name="<?php echo VGEVE; ?>txt_impuesto" readonly  >
                                        </label>
                                  </div> 
                                  <label class="label col col-2"><?php echo VGEVE_30; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-money"></i>
                                            <input style="text-align: right;background: #eee;" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_totalPago" name="<?php echo VGEVE; ?>txt_totalPago" readonly  >
                                        </label>
                                  </div> 
                             </div>
                        </section>                                                
                        <section>    
                             <div class="row">
                                  <label class="label col col-2"><?php echo VGEVE_24; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-money"></i>
                                            <input style="text-align: right; background: #eee;" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_totalF" name="<?php echo VGEVE; ?>txt_totalF" readonly >
                                        </label>
                                  </div>
                                  <label class="label col col-2"><?php echo VPROD8; ?></label>
                                    <div class="col col-2">
                                        <label class="checkbox">
                                            <input type="checkbox" name="<?php echo VGEVE; ?>chk_impuesto" id="<?php echo VGEVE; ?>chk_impuesto" value="1" onclick="generarVentaScript.calcularImpuesto();" disabled ></input>
                                            <i></i>
                                            <?php echo LABEL_S; ?>
                                        </label>
                                    </div>                                  
                             </div>
                        </section>
                        <section> 
                            <hr>                            
                        </section>
                        <section>
                            <div class="row">
                                <div class="alert alert-success ">
                                     <i class="fa fa-money"></i> Paso 4: Ahora, ingrese la cantidad que pagará el Cliente y los datos de facturación:
                                </div>
                            </div>
                        </section>          
                        <section>    
                             <div class="row">                                  
                                  <label class="label col col-2"><?php echo VGEVE_42; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-money"></i>
                                            <input style="text-align: right; background: #eee;" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_pagado" name="<?php echo VGEVE; ?>txt_pagado" value="<?php echo number_format($datac['monto_asignado'],2);?>" readonly >
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo VGEVE_42M; ?></b>
                                        </label>
                                  </div>
                                  <div class="col col-8">
                                      <div class="alert alert-info ">
                                        <i class="fa fa-info-circle"></i> Este dinero ingresará como egreso en su caja.
                                    </div>
                                  </div>
                             </div>
                        </section>                       
                        <section>    
                             <div class="row">                                  
                                  <label class="label col col-2"><?php echo VGEVE_25; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-money txt-color-white"></i>
                                            <input style="text-align: right;" class="form-control bg-color-red txt-color-white"  type="text" id="<?php echo VGEVE; ?>txt_pago" name="<?php echo VGEVE; ?>txt_pago"   >
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo VGEVE_25M; ?></b>
                                        </label>
                                  </div>
                                  <label class="label col col-2"><?php echo VGEVE_38; ?></label>
                                  <div class="col col-2">
                                       <label class="select"> 
                                          <?php
                                              $metodoPago = metodoPagoController::findMetodoPagoAll();
                                              echo Functions::selectHtml(array(
                                                  'data'=>$metodoPago,
                                                  'atributes'=>array(
                                                      'id'=>VGEVE.'lst_metodoPago',
                                                      'name'=>VGEVE.'lst_metodoPago'                                           
                                                  ),
                                                  'etiqueta'=>'descripcion',
                                                  'value'=>'id',
                                                  'defaultEtiqueta'=>'1',                                                
                                                  'encript'=>true
                                              ));
                                              ?> <i></i>  
                                        </label>
                                    </div>  
                                  <label class="label col col-2"><?php echo VGEVE_39; ?> </label>
                                  <div class="col col-2">
                                        <label class="input"> 
                                            <i class="icon-append fa fa-file-text-o"></i>
                                            <input class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_operacion" name="<?php echo VGEVE; ?>txt_operacion"   >
                                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo VGEVE_39M; ?></b>
                                        </label>
                                  </div>
                             </div>
                        </section>                                                
                        <section >
                            <div class="row">
                                <label class="label col col-2"><?php echo VGEVE_8; ?> </label>
                                <div class="col col-2">
                                      <label class="select"> 
                                         <?php
                                             $dataDoc = generarVentaController::getTipoDocumento();                          
                                              echo Functions::selectHtml(array(
                                                  'data'=>$dataDoc,
                                                  'atributes'=>array(
                                                      'id'=>VGEVE.'lst_tipoDoc',
                                                      'name'=>VGEVE.'lst_tipoDoc'
                                                  ),
                                                  'etiqueta'=>'descripcion',
                                                  'value'=>'id',
                                                  'defaultEtiqueta'=>'0',
                                                  'txtSelect'=>false                                         
                                             ));
                                      ?> <i></i>                                 
                                      </label>  
                                </div>
                                <label class="label col col-2"><?php echo VSEVE_5; ?> </label>
                                <div class="col col-2">
                                     <label class="input"> 
                                         <i class="icon-append fa fa-file-text"></i>
                                         <input maxlength="10" style="text-align: right" class="form-control"  type="text" id="<?php echo VGEVE; ?>txt_serie" name="<?php echo VGEVE; ?>txt_serie"   >
                                         <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo VSEVE_5M; ?></b>
                                     </label>
                                 </div>  
                                 <label class="label col col-2"><?php echo VSEVE_6; ?> </label>
                                 <div class="col col-2">
                                     <label class="input"> 
                                         <i class="icon-append fa fa-file-text"></i>
                                         <input maxlength="20" style="text-align: right" type="text" id="<?php echo VGEVE; ?>txt_numero" name="<?php echo VGEVE; ?>txt_numero" >                                      
                                         <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo VSEVE_6M; ?></b>
                                     </label>
                                 </div>
                             </div>
                    </section>                        
                    <section>
                        <div class="row">
                            <label class="label col col-xs-2" for="prepend"><?php echo LABEL_OBS; ?></label>
                            <div class="col col-xs-10">
                                <div class="textarea">
                                    <textarea class="obs form-control" id="<?php echo VGEVE; ?>txt_obs" name="<?php echo VGEVE; ?>txt_obs"><?php echo nl2br($obs); ?></textarea>
                                </div>
                            </div>
                       </div>
                    </section>  
                    <br><hr><br>                           
                    <h4 class="text-center">
                        <button id="<?php echo VMOVE; ?>btnEdVenta" type="button" class="btn btn-success btn-large padding-10" onclick="javascript:editarVenta()">    
                            <i class="fa fa-plus-circle fa-lg"></i>
                            <?php echo VGEVE_23; ?>
                        </button>
                    </h4>
            </div>
</form>              
<script>    
    generarVentaScript.calculoTotalFilaUp();    
    generarVentaScript.calculoTotal();     
    $('#'+diccionario.tabs.VGEVE+'lst_igv').val('S');
    $('#'+diccionario.tabs.VGEVE+'lst_igv').change();                        
    $("#"+diccionario.tabs.VGEVE+"chk_impuesto").prop("checked", "");
    $("#"+diccionario.tabs.VGEVE+"chk_impuesto").attr("disabled","disabled");
    $('#'+diccionario.tabs.VGEVE+'txt_totalPago').val(0);
    
    var pagefunction = function() {
         $('.editable').summernote({
                        height : 120,
                        focus : true,                  
                        lang: 'es-ES',
                        toolbar: [
                        ['font', ['bold','italic' ,'underline', 'clear', 'codeview' ]]
                      ]
                    });		
                    
        $('.obs').summernote({
                        height : 100,
                        focus : true,                  
                        lang: 'es-ES',
                        toolbar: [
                        ['font', ['bold','italic' ,'underline', 'clear', 'codeview' ]]
                      ]
                    });		
    };	
    loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/summernote/summernote.min.js", function(){
        loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/summernote/lang/summernote-es-ES.min.js", function(){
            loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/markdown/markdown.min.js", function(){
                            loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/markdown/bootstrap-markdown.min.js", pagefunction);
            });
        });
    });
        
    simpleScript.chosen({'id':'#<?php echo VGEVE; ?>lst_sucursal'});  
    
    var $validator = $("#<?php echo VMOVE; ?>formEditGenerarVenta").validate({
        rules: {
                <?php echo VGEVE; ?>txt_cliente: {
                    required: true
                },
                <?php echo VGEVE; ?>txt_codImpr: {
                    required: true,
                    number:true
                },  
               <?php echo VGEVE; ?>txt_pago: {
                    required: true,
                    number: true                    
                },<?php echo VGEVE; ?>lst_caja : {
                    required : true
                },<?php echo VGEVE; ?>txt_totalF : {
                    required : true,
                    number:true
                } 
        } 
    });
    
    function editarVenta(){            
        var $valid = $("#<?php echo VMOVE; ?>formEditGenerarVenta").valid();
        if (!$valid) {
            $validator.focusInvalid();
            return false;
        }else{
            var pr = 0;
            var dd = 0;
            var r = simpleScript.validaTable({
                id: '#'+diccionario.tabs.VGEVE+'gridProductos',
                msn: lang.mensajes.MSG_10
            });

            //Validar que precios no sean 0                      
              $('#'+diccionario.tabs.VGEVE+'gridProductos tbody tr').each(function (index) {
                    var precio;
                    $(this).children("td").each(function (index2) {
                      switch (index2) {
                          case 6:
                              precio = $(this).text();
                               if(parseFloat(precio) <= 0 || isNaN(parseFloat(precio)) ){   
                                    pr = pr + 1;                                      
                                }
                              break;      
                      }
                  });
              });
              
              $('#'+diccionario.tabs.VGEVE+'gridProductos tbody tr').each(function (index) {
                    var serv;
                    $(this).children("td").each(function (index2) {
                      switch (index2) {
                          case 0:                              
                             serv = $(this).find('div.note-editable').html();    
                             if (serv !== undefined){
                                serv = serv.length;
                                if(serv <= 11 ){   
                                       dd = dd + 1;                                      
                                }
                            }                                
                            break;      
                      }
                    });
              });
            if (dd > 0){
                simpleScript.notify.warning({
                    content: 'Debe de ingresar Descripción del Servicio, es importante este dato.'
                }); 
               return false;
           }else if (pr > 0){
                simpleScript.notify.warning({
                    content: 'El precio que ingreso en la tabla, es menor o igual que CERO (0.00), por favor verificar.'
                }); 
               return false;
            }else if(r === false){
                return false;
            }
            var totalPagado= simpleScript.deleteComa($('#'+diccionario.tabs.VGEVE+'txt_totalF').val());        
            var acuenta = simpleScript.deleteComa($('#'+diccionario.tabs.VGEVE+'txt_pago').val());        
            var pagoAnterior = simpleScript.deleteComa($('#'+diccionario.tabs.VGEVE+'txt_pagado').val());        
            if(isNaN(acuenta) || acuenta == '' ){acuenta = 0;}        
            if(parseFloat(totalPagado) <= 0){
                 simpleScript.notify.warning({
                     content: 'El total a pagar no debe ser Cero'
                 });
                 return false;
             }else if(parseFloat(totalPagado) < parseFloat(pagoAnterior + acuenta)){
                simpleScript.notify.warning({
                     content: 'El pago inicial + el pago anterior, es mayor que el total a pagar. Por favor verificar.'
                 });
                 return false;          
            }                        
          modificarVenta.postEditarGenerarVenta();
        }
    };

        /*para hacer evento invisible*/
       simpleScript.removeAttr.click({
           container: '#<?php echo VMOVE; ?>formEditGenerarVenta',
           typeElement: 'button'
       });
       simpleScript.removeAttr.keyup({
           container: '#<?php echo VMOVE; ?>formEditGenerarVenta',
           typeElement: 'input'
       });

       simpleScript.setEvent.blur({   
               element:'.editable',
               event: function(){      
                   $('textarea[name="content"]').html($('.editable').summernote('code'));  
               }
       });                                         
</script>
