<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 22-11-2014 20:11:18 
* Descripcion : formNewVegresos.phtml
* ---------------------------------------
*/

/*prefijo: VEGRE debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("VEGREGR");

if( Session::get('sys_visible') == 'S' ){
    $idSucursal = 1; // Administrador por defecto 1. Ya al seleccionar el combo se mostrara los demas cajas x sucursal.
}else{
    $idSucursal = Session::get('sys_idSucursal'); // Sucursal configurada desde usuarios para el cajero.
}

?>
<form id="<?php echo VEGRE; ?>formNewVegresos" name="<?php echo VEGRE; ?>formNewVegresos" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VEGRE_2; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <?php  if( Session::get('sys_visible') == 'S' ): ?>   
                    <section >
                          <div class="row">                              
                              <label class="label col col-2"><?php echo VGEVE_15; ?>  </label>
                              <div class="col col-10">
                                    <label class="select" > 
                                       <?php
                                           $dataSucursal = vSucursalController::getSucursalAll('S');
                                               echo Functions::selectHtml(array(
                                                   'data'=>$dataSucursal,
                                                   'atributes'=>array(
                                                       'id'=>VEGRE.'lst_sucursal',
                                                       'name'=>VEGRE.'lst_sucursal',  
                                                        'onchange'=>'cajaApertura.getCaja({
                                                            idSucursal: $(\'#'.VEGRE.'lst_sucursal\').val(),
                                                            content: \'#'.VEGRE.'cont-caja\',
                                                            idElement: \''.VEGRE.'lst_caja\',
                                                            nameElement: \''.VEGRE.'lst_caja\',
                                                            onchange: \'\'   
                                                        }); vegresos.getBeneficiario({
                                                            idSucursal: $(\'#'.VEGRE.'lst_sucursal\').val(),
                                                            content: \'#'.VEGRE.'cont-beneficiario\',
                                                            idElement: \''.VEGRE.'lst_beneficiario\',
                                                            nameElement: \''.VEGRE.'lst_beneficiario\'                                                         
                                                        });'
                                                   ),  
                                                   'etiqueta'=>'descripcion',
                                                   'value'=>'id',
                                                   'defaultEtiqueta'=>$idSucursal,
                                                   'txtSelect'=>true,
                                                   'encript' => true
                                           ));
                                    ?><i></i>                                  
                                    </label>                                                                                           
                                </div>
                          </div>
                    </section>
                     <?php endif; ?>
                <section >
                          <div class="row">                             
                              <label class="label col col-2"><?php echo VGEVE_33; ?>  </label>
                              <div class="col col-10">
                                    <label class="select" id="<?php echo VEGRE; ?>cont-caja"> 
                                       <?php
                                           $dataCaja = cajaAperturaController::getDataCajaAll($idSucursal);
                                               echo Functions::selectHtml(array(
                                                   'data'=>$dataCaja,
                                                   'atributes'=>array(
                                                       'id'=>VEGRE.'lst_caja',
                                                       'name'=>VEGRE.'lst_caja',                                            
                                                   ),  
                                                   'etiqueta'=> 'descripcion',
                                                   'value'=>'id_caja',
                                                   'defaultEtiqueta'=>'',
                                                   'txtSelect'=>false,
                                                   'encript' => true
                                           ));
                                               ?> <i></i>                                 
                                    </label>                                                                                           
                              </div>
                          </div>
                    </section>               
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VEGRE_5; ?></label>
                        <div class="col col-10">
                            <div class="textarea">
                                <textarea class="form-control" id="<?php echo VEGRE; ?>txt_descripcion" name="<?php echo VEGRE; ?>txt_descripcion"></textarea>
                                 <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VEGRE_5M; ?></b>
                            </div>
                        </div>
                    </div>
                </section>
                <section >
                          <div class="row">                             
                              <label class="label col col-2"><?php echo VEGRE_6; ?>  </label>
                              <div class="col col-10">
                                    <label class="select" id="<?php echo VEGRE; ?>cont-beneficiario"> 
                                       <?php
                                           $dataBeneficiario = vegresosController::getFindDataBeneficiarioAll($idSucursal);
                                               echo Functions::selectHtml(array(
                                                   'data'=>$dataBeneficiario,
                                                   'atributes'=>array(
                                                       'id'=>VEGRE.'lst_beneficiario',
                                                       'name'=>VEGRE.'lst_beneficiario',                                            
                                                   ),  
                                                   'etiqueta'=> 'persona',
                                                   'value'=>'id_persona',
                                                   'group'=>'tipo',
                                                   'defaultEtiqueta'=>'',
                                                   'txtSelect'=>true,
                                                   'encript' => true
                                           ));
                                        ?>                               
                                    </label>                                                                                           
                              </div>
                          </div>
                    </section>  
                 <section>
                    <div class="row">                                        
                        <label class="label col col-2"><?php echo VEGRE_4; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-money"></i>
                                <input style="text-align: right" type="text" id="<?php echo VEGRE; ?>txt_monto" name="<?php echo VEGRE; ?>txt_monto">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VEGRE_4M; ?></b>
                            </label>
                        </div>                                             
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo VEGRE; ?>btnGrVegresos" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VEGRE; ?>formNewVegresos");
</script>
<?php endif; ?>
<script>
   $("#<?php echo VEGRE; ?>formNewVegresos").removeAttr('tabindex');
   simpleScript.chosen({'id':'#<?php echo VEGRE; ?>lst_beneficiario'});
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo VEGRE; ?>formNewVegresos").validate({
    rules : {
        <?php echo VEGRE; ?>txt_descripcion : {
            required : true,
            minlength: 3
        },
        <?php echo VEGRE; ?>txt_monto : {
            required : true,
            number: true
        },<?php echo VEGRE; ?>lst_caja : {
            required : true
        } 
    },   
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        vegresos.postNewVegresos();
    }   
});
</script>