<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-11-2014 17:11:18 
* Descripcion : formNewVcliente.phtml
* ---------------------------------------
*/

/*prefijo: VRECL debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("VRECLGR");
$idUbigeo = '001020140';
//style="height: 350px;overflow-y: auto;overflow-x: hidden;"
?>
<form id="<?php echo VRECL; ?>formNewVcliente" name="<?php echo VRECL; ?>formNewVcliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VRECL_2;?></h4>
            </div>
          <div class="modal-body smart-form" >    
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VRECL_6; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input maxlength="8" type="text" id="<?php echo VRECL; ?>txt_nrodocumento" name="<?php echo VRECL; ?>txt_nrodocumento">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VRECL_6M; ?></b>
                            </label>
                        </div>
                        <label class="label col col-2"><?php echo VRECL_7; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input maxlength="11" type="text" id="<?php echo VRECL; ?>txt_ruc" name="<?php echo VRECL; ?>txt_ruc">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo VRECL_7M; ?></b>
                            </label>
                        </div>          
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV4; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_empresa" name="<?php echo VRECL; ?>txt_empresa">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_RV7; ?></b>
                            </label>
                        </div>
                    </div>
                </section>   
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo VRECL_4; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-user"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_nombres" name="<?php echo VRECL; ?>txt_nombres">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo LABEL_RV6; ?></b>
                            </label>
                        </div>
                    </div>
                </section>                                                      
              <!--                                                                                 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV26; ?></label>
                        <div class="col col-10">
                            <label class="select"> 
                                <?php
                                    $datap = ubigeoController::getPais();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$datap,
                                        'atributes'=>array(
                                            'id'=>VRECL.'lst_pais',
                                            'name'=>VRECL.'lst_pais',
                                            'onchange'=>'ubigeo.getDepartamento({
                                                            idPais: $(\'#'.VRECL.'lst_pais\').val(),
                                                            content: \'#'.VRECL.'cont-departamentos\',
                                                            idElement: \''.VRECL.'lst_departamentos\',
                                                            nameElement: \''.VRECL.'lst_departamentos\',                                                            
                                                            contentUbigeo: \'#'.VRECL.'cont-ubigeo\',
                                                            idUbigeo: \''.VRECL.'lst_ubigeo\'
                                                        });'
                                        ),
                                        'etiqueta'=>'pais',
                                        'value'=>'id_pais',
                                        'encript'=>true,
                                        'defaultEtiqueta'=>substr($idUbigeo, 0,3),
                                        'txtSelect'=>true
                                    ));
                                    
                                ?>
                            </label>
                        </div>
                    </div>
                </section>   -->             
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV18; ?></label>
                        <div class="col col-10">
                            <label class="select" id="<?php echo VRECL; ?>cont-departamentos"> 
                                <?php 
                                    $datad = ubigeoController::getDepartamentosEst(substr($idUbigeo, 0,3));
                                    echo Functions::selectHtml(array(
                                        'data'=>$datad,
                                        'atributes'=>array(
                                            'id'=>VRECL.'lst_departamento',
                                            'name'=>VRECL.'lst_departamento',
                                            'onchange'=>'ubigeo.getUbigeo({
                                                            idDepartamento: $(\'#'.VRECL.'lst_departamento\').val(),
                                                            content: \'#'.VRECL.'cont-ubigeo\',
                                                            idElement: \''.VRECL.'lst_ubigeo\',
                                                            nameElement: \''.VRECL.'lst_ubigeo\'                                                         
                                                        });'
                                        ),
                                        'etiqueta'=>'departamento',
                                        'value'=>'id_departamento',
                                        'encript'=>true,
                                        'defaultEtiqueta'=> substr($idUbigeo, 0,5),
                                        'txtSelect'=>true
                                    ));
                                ?>
                            </label>
                        </div>
                    </div>
                </section>            
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV20; ?></label>
                        <div class="col col-10">
                            <label class="select" id="<?php echo VRECL; ?>cont-ubigeo"> 
                                <?php 
                                    $datau = ubigeoController::getUbigeoEst(substr($idUbigeo, 0,5));
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$datau,
                                        'atributes'=>array(
                                            'id'=>VRECL.'lst_ubigeo',
                                            'name'=>VRECL.'lst_ubigeo'
                                        ),
                                        'etiqueta'=>'distrito',
                                        'value'=>'id_ubigeo',
                                        'encript'=>true,
                                        'defaultEtiqueta'=> $idUbigeo,
                                        'txtSelect'=>true
                                    ));
                                ?>
                            </label>
                        </div>
                    </div>
                </section>     
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV9; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_direccion" name="<?php echo VRECL; ?>txt_direccion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV11; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV10; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_email" name="<?php echo VRECL; ?>txt_email">
                                <a href="http://www.verifyemailaddress.org/" target="_blank">Verificar Correo</a>
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV12; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
              <!--
                <section class="frmpn">
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV13; ?></label>
                        <div class="inline-group col col-10">
                            <label class="radio"> 
                                <input name="<?php echo VRECL; ?>rd_sexo" id="<?php echo VRECL; ?>rd_sexoH" checked type="radio" value="H">
                                <i></i>Hombre
                            </label>
                            <label class="radio"> 
                                <input name="<?php echo VRECL; ?>rd_sexo" id="<?php echo VRECL; ?>rd_sexoM" type="radio" value="M">
                                <i></i>Mujer
                            </label>
                        </div>
                    </div>
                </section>-->
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_RV14; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo VRECL; ?>txt_telefonos" name="<?php echo VRECL; ?>txt_telefonos">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_RV15; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div> 
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo VRECL; ?>btnGrVcliente" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo VRECL; ?>formNewVcliente");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/

    simpleScript.chosen({'id':'#<?php echo VRECL; ?>lst_pais'});    
    simpleScript.chosen({'id':'#<?php echo VRECL; ?>lst_departamento'});   
    simpleScript.chosen({'id':'#<?php echo VRECL; ?>lst_ubigeo'});      
    
    $("#<?php echo VRECL; ?>formNewVcliente").removeAttr('tabindex');

    $("#<?php echo VRECL; ?>formNewVcliente").validate({
        rules : {
                    <?php echo VRECL; ?>txt_nombres : {                            
                            minlength: 3
                    },
                    <?php echo VRECL; ?>txt_empresa : {
                            minlength: 2
                    },                               
                    <?php echo VRECL; ?>txt_email : {                           
                            email: true
                    },
                    <?php echo VRECL; ?>txt_nrodocumento : {                        
                            number: true,
                            maxlength: 8
                    },
                    <?php echo VRECL; ?>txt_ruc : {                        
                            number: true,
                            maxlength: 11
                    },
                    <?php echo VRECL; ?>lst_ubigeo : {
                            required : true
                    }
        },
        errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
        },

        submitHandler: function(){
            vCliente.postNewVcliente();
        }   
       });

</script>