<?php
/*
 * Documento   : buscarCliente de manera Global
 * Creado      : 05-04-2016
 */

$buscar = $this->buscar;
$nuevo = $this->nuevo;
$ventana = $this->ventana;
?>
<form id="<?php echo $ventana; ?>formBuscarCliente" name="<?php echo $ventana; ?>formBuscarCliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" onsubmit="return false;">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo VRECL_8; ?></h4>
            </div>
            <div class="modal-body smart-form scroll-form" style="padding:10px;"  >
                <div class="modal-body smart-form scroll-form"  >
                 <div class="widget-body-toolbar">                     
                 </div>
                <div class="dataTables_wrapper form-inline" role="grid">
                    <div class="dt-top-row">
                        <div class="DTTT btn-group">
                            <!-- verificar permisos -->
                            <?php if($nuevo['permiso']): ?>
                            <button id="<?php echo $ventana; ?>newCliente" type="button" onclick="vCliente.getFormNewVcliente(this,'#<?php echo $ventana; ?>formBuscarCliente');" class="<?php echo $nuevo['theme'];?>" title="Nuevo Cliente" style="padding:5px 10px;">
                                 <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                            </button>
                            <?php endif; ?>     
                        </div>
                    </div>
                </div>
                <table id="<?php echo $ventana; ?>gridClientesFound" class="table table-striped table-hover table-condensed" style="width:100%;"></table>                          
             </div>
                <div class="modal-body smart-form"  style="padding: 0 0 0 10px;"  >
                 <section>
                    <div class="row">
                        <label class="label col col-2">
                        <?php echo LABEL_LEYENDA; ?>
                        </label>
                        <div class="col col-9 ">                            
                            <?php if($buscar["permiso"]): ?>
                            <button type="button" class="<?php echo $buscar['theme']; ?> margin-top-5 padding-5" title="<?php echo LABEL_SELECCIONAR; ?>" ><i class="<?php echo $buscar['icono'];?>"></i>  <?php echo LABEL_SELECCIONAR; ?> </button>                    
                            <?php endif;?>
                        </div>
                    </div>
                </section>    
            </div>  
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$buscar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo $ventana; ?>formBuscarCliente');
    </script>
<?php endif; ?>