<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 07-04-2016 17:04:08 
* Descripcion : indexReporteVendedor.phtml
* ---------------------------------------
*/

$recargar    = Session::getPermiso("VRPT4REC");
$exportarpdf   = Session::getPermiso('VRPT4EP');
$exportarexcel = Session::getPermiso('VRPT4EX');   
$buscar    = Session::getPermiso("VRPT4BS");
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VRPT4,
        "title"=>"ReporteVendedor"
    )); 
?>
<button id="<?php echo VRPT4; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VRPT4; ?>btnDowExcel" type="button" class="hide">Descargar</button>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 0px;top:5px">
        <div class="container">
            <div class="row">
                <div class="col-xs-10">
                    <div class="container-fluid">            
                        <div class="row">          
                            <label class="label col col-xs-1 text-align-right font-xs">&nbsp;<?php echo LABEL_DESDE; ?></label>                                    
                            <div class="col col-xs-2">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    <input class="form-control" type="text" id="<?php echo VRPT4;?>txt_f1" 
                                           name="<?php echo VRPT4;?>txt_f1" value ="01/01/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " />
                                 </div>            
                            </div>
                            <label class="label col col-xs-1 text-align-right font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
                            <div class="col col-xs-2">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    <input class="form-control" type="text" id="<?php echo VRPT4;?>txt_f2" 
                                           name="<?php echo VRPT4;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " />
                                 </div>            
                            </div>                                                     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>              
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($recargar["permiso"]): ?>
                <button id="<?php echo VRPT4; ?>gridReporteVendedor_btnRecarga" type="button" onclick="reporteVendedor.getGridReporteVendedor();" class="<?php echo $recargar["theme"]; ?>">
                    <i class="<?php echo $recargar["icono"]; ?>"></i> <?php echo $recargar["accion"]; ?>
                </button>
                <?php endif; ?>    
            </div>
        </div>

    </div>    
    <table id="<?php echo VRPT4; ?>gridReporteVendedor" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
        
 <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($exportarpdf["permiso"]): ?>
                        <button type="button" class="<?php echo $exportarpdf["theme"]; ?> margin-top-5" title="<?php echo $exportarpdf["accion"]; ?>" ><i class="<?php echo $exportarpdf["icono"];?>"></i>  <?php echo $exportarpdf["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                    <?php if($exportarexcel["permiso"]): ?>
                        <button type="button" class="<?php echo $exportarexcel["theme"]; ?> margin-top-5" title="<?php echo $exportarexcel["accion"]; ?>" ><i class="<?php echo $exportarexcel["icono"];?>"></i>  <?php echo $exportarexcel["accion"]; ?> </button>                    
                    <?php endif;?>      
                </div>
            </div>

        </section>
    </div>

<?php echo Functions::widgetClose(); ?>
<script>
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VRPT4; ?>txt_f1',
        fin: '#<?php echo VRPT4; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VRPT4; ?>txt_f2',
        fin: '#<?php echo VRPT4; ?>txt_f1',
        opt: 'maxDate'
    });  
    simpleScript.setEvent.change({
        element: '#<?php echo VRPT4; ?>txt_f1, #<?php echo VRPT4; ?>txt_f2',
        event: function(){reporteVendedor.getGridReporteVendedor()}
    })   
</script>