<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-11-2014 22:11:42 
* Descripcion : indexVConsultaSaldo.phtml
* ---------------------------------------
*/
$pdf   = Session::getPermiso('VCSCLEP');
$excel = Session::getPermiso('VCSCLEX');    
echo Functions::widgetOpen(array(
        "id"=>VCSCL,
        "title"=>VCSCL_1,
        'actions' => array( 
             array(
                    'id' => VCSCL . 'btnPDF',                    
                    'permiso'=> 'VCSCLEP',
                    'click' => 'vConsultaSaldo.postPDFGeneral();'                    
                ),
               array(
                    'id' => VCSCL . 'btnExcel',                    
                    'permiso'=> 'VCSCLEX',
                    'click' => 'vConsultaSaldo.postExcelGeneral();'                    
                ),
                array(
                    'id' => VCSCL . 'gridVConsultaSaldo_btnRecarga',                    
                    'permiso'=> 'VCSCLREC',
                    'click' => 'vConsultaSaldo.getGridVConsultaSaldo();'                    
                )
            )
    )); 
?>
<button id="<?php echo VCSCL; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VCSCL; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left: 250px;top:5px;width: 65% ">                  
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-3 " style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VCSCL.'lst_sucursalGrid',
                                'name'=>VCSCL.'lst_sucursalGrid',   
                                'onchange'=>'vConsultaSaldo.getGridVConsultaSaldo();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>
    
    
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
             
            </div>
        </div>

    </div>
    <table id="<?php echo VCSCL; ?>gridVConsultaSaldo" class="table table-striped table-hover table-condensed" style="width:100%"></table>
     <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($pdf["permiso"]): ?>
                        <button type="button" class="<?php echo $pdf["theme"]; ?> margin-top-5" title="<?php echo $pdf["accion"]; ?>" ><i class="<?php echo $pdf["icono"];?>"></i>  <?php echo $pdf["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                    <?php if($excel["permiso"]): ?>
                        <button type="button" class="<?php echo $excel["theme"]; ?> margin-top-5" title="<?php echo $excel["accion"]; ?>" ><i class="<?php echo $excel["icono"];?>"></i>  <?php echo $excel["accion"]; ?> </button>                    
                    <?php endif;?>       
                </div>
            </div>

        </section>
    </div>
<?php echo Functions::widgetClose(); ?>
<script>

    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VCSCL; ?>txt_f1',
        fin: '#<?php echo VCSCL; ?>txt_f2',
        opt: 'minDate'
    });
    
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VCSCL; ?>txt_f2',
        fin: '#<?php echo VCSCL; ?>txt_f1',
        opt: 'maxDate'
    });       
    
</script>