<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-11-2014 17:11:41 
* Descripcion : indexVseguimientoventa.phtml
* ---------------------------------------
*/
$recargar = Session::getPermiso("VSEVEREC");
$pagar   = Session::getPermiso('VSEVEPG');
$exportarpdf   = Session::getPermiso('VSEVEEP');
$editar   = Session::getPermiso('VSEVEED');

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VSEVE,
        "title"=>VSEVE_1,
        'actions' => array(               
                array(
                    'id' => VSEVE . 'gridVseguimientoventa_btnRecarga',                    
                    'permiso'=> 'VSEVEREC',
                    'click' => 'vseguimientoventa.getGridVseguimientoventa();'                    
                )
            )
    )); 
        
?>
<button id="<?php echo VSEVE; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left:300px;top:5px; width: 50%">                       
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-3" style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VSEVE.'lst_sucursalGrid',
                                'name'=>VSEVE.'lst_sucursalGrid',   
                                'onchange'=>'vseguimientoventa.getGridVseguimientoventa();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>      
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">                                
            </div>
        </div>
    </div>
    <table id="<?php echo VSEVE; ?>gridVseguimientoventa" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">                      
                     <?php if($pagar["permiso"]): ?>
                    <button type="button" class="<?php echo $pagar['theme']; ?> margin-top-5" title="<?php echo $pagar['accion']; ?>" ><i class="<?php echo $pagar['icono'];?>"></i>  <?php echo $pagar['accion']; ?>  </button>                                        
                    <?php endif;?>   
                    <?php if($exportarpdf["permiso"]): ?>
                    <button type="button" class="<?php echo $exportarpdf['theme']; ?> margin-top-5" title="<?php echo $exportarpdf['accion']; ?>" ><i class="<?php echo $exportarpdf['icono'];?>"></i>  <?php echo  $exportarpdf['accion']; ?>  </button>                                        
                    <?php endif;?>             
                    <?php if($editar["permiso"]): ?>
                    <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?>  </button>                                        
                    <?php endif;?> 
                </div>
            </div>
        </section>
    </div>    
<?php echo Functions::widgetClose(); ?>