<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-05-2016 17:05:16 
* Descripcion : indexReporteResumenCliente.phtml
* ---------------------------------------
*/
$pdf   = Session::getPermiso('VRPT5EP');
$excel = Session::getPermiso('VRPT5EX');
    
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VRPT5,
        "title"=>VRPT5_1,
        "actions" => array(               
                array(
                    "id" => VRPT5 . "gridReporteResumenCliente_btnRecarga",                    
                    "permiso"=> "VRPT5REC",
                    "click" => "reporteResumenCliente.getGridReporteResumenCliente();"                  
                )
            )
    )); 
?>
<button id="<?php echo VRPT5; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VRPT5; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left:250px;top:5px; width: 50%">               
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VRPT5;?>txt_f1" name="<?php echo CAJAA;?>txt_f1" value ="<?php echo date("01/01/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VGEVE; ?>gridGenerarVenta_btnRecarga',event);" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-3" style="padding-left:10px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VRPT5;?>txt_f2" name="<?php echo CAJAA;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VGEVE; ?>gridGenerarVenta_btnRecarga',event);" />
             </div>            
        </div>
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-3 " style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VRPT5.'lst_sucursalGrid',
                                'name'=>VRPT5.'lst_sucursalGrid',   
                                'onchange'=>'generarVenta.getGridGenerarVenta();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>               
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->                          
            </div>
        </div>

    </div>    
    <table id="<?php echo VRPT5; ?>gridReporteResumenCliente" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
        
<?php echo Functions::widgetClose(); ?>