<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-11-2014 16:11:31 
* Descripcion : indexVunidadMedida.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VUNIDNEW");
$eliminar = Session::getPermiso("VUNIDDE");
$editar = Session::getPermiso("VUNIDED");
$recargar = Session::getPermiso("VUNIDREC");
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VUNID,
        "title"=>VUNID1,
        'actions' => array(                    
                array(
                    'id' => VUNID . 'gridVunidadMedida_btnRecarga',                    
                    'permiso'=> 'VUNIDREC',
                    'click' => 'vunidadMedida.getGridVunidadMedida();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo VUNID; ?>btnNewVunidadMedida" type="button" onclick="vunidadMedida.getFormNewVunidadMedida(this,'');" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>              
            </div>
        </div>

    </div>    
    <table id="<?php echo VUNID; ?>gridVunidadMedida" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">                      
                    <?php if($editar["permiso"]): ?>
                    <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?> </button>                    
                    <?php endif;?>
                     <?php if($eliminar["permiso"]): ?>
                    <button type="button" class="<?php echo $eliminar['theme']; ?> margin-top-5" title="<?php echo $eliminar['accion']; ?>" ><i class="<?php echo $eliminar['icono'];?>"></i>  <?php echo $eliminar['accion']; ?>  </button>                                        
                    <?php endif;?>                                         
                </div>
            </div>
        </section>
    </div>
    
<?php echo Functions::widgetClose(); ?>