<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 05-04-2016 18:04:07 
* Descripcion : indexVSucursal.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("SUCURNEW");
$editar    = Session::getPermiso("SUCURED");
$eliminar    = Session::getPermiso("SUCURADE");
$recargar    = Session::getPermiso("SUCURREC");
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>SUCUR,
        "title"=>SUCUR_01,
        'actions' => array(               
                array(
                    'id' => SUCUR . 'gridVSucursal_btnRecarga',                    
                    'permiso'=> 'SUCURREC',
                    'click' => 'vSucursal.getGridVSucursal();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo SUCUR; ?>btnNewVSucursal" type="button" onclick="vSucursal.getFormNewVSucursal(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>     
            </div>
        </div>

    </div>    
    <table id="<?php echo SUCUR; ?>gridVSucursal" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
        
 <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar["theme"]; ?> margin-top-5" title="<?php echo $editar["accion"]; ?>" ><i class="<?php echo $editar["icono"];?>"></i>  <?php echo $editar["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                    <?php if($eliminar["permiso"]): ?>
                        <button type="button" class="<?php echo $eliminar["theme"]; ?> margin-top-5" title="<?php echo $eliminar["accion"]; ?>" ><i class="<?php echo $eliminar["icono"];?>"></i>  <?php echo $eliminar["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                            
                </div>
            </div>

        </section>
    </div>

<?php echo Functions::widgetClose(); ?>