<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 14-11-2014 09:50:58 
* Descripcion : indexGenerarVenta.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("VGEVENEW");
$anular = Session::getPermiso("VGEVEAN");
$exportarpdf   = Session::getPermiso('VGEVEEP');
$exportarexcel = Session::getPermiso('VGEVEEX');   
$recargar = Session::getPermiso("VGEVEREC");
$pagar   = Session::getPermiso('VGEVEPG');

echo Functions::siteMap();

//'sitemap' => Session::get('0026')
echo Functions::widgetOpen(array(
        "id"=>VGEVE,
        "title"=>VGEVE_1,
        'actions' => array(               
                array(
                    'id' => VGEVE . 'gridGenerarVenta_btnRecarga',                    
                    'permiso'=> 'VGEVEREC',
                    'click' => 'generarVenta.getGridGenerarVenta();'                    
                )
            )
    )); 
if( Session::get('sys_visible') == 'N' ){
    $validarCaja = cajaAperturaController::getValidarCaja()['existe'];    
}else{
    $validarCaja = 1;
}

?>
<button id="<?php echo VGEVE; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VGEVE; ?>btnDowExcel" type="button" class="hide">Descargar</button>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:250px;top:5px; width: 50%">               
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VGEVE;?>txt_f1" name="<?php echo CAJAA;?>txt_f1" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VGEVE; ?>gridGenerarVenta_btnRecarga',event);" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-3" style="padding-left:10px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VGEVE;?>txt_f2" name="<?php echo CAJAA;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VGEVE; ?>gridGenerarVenta_btnRecarga',event);" />
             </div>            
        </div>
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-3 " style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VGEVE.'lst_sucursalGrid',
                                'name'=>VGEVE.'lst_sucursalGrid',   
                                'onchange'=>'generarVenta.getGridGenerarVenta();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>               
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"] ): ?>
                    <?php if($validarCaja > 0 ): ?>
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" onclick="generarVenta.getFormNewGenerarVenta(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo VGEVE_35;?>
                </button>   
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta2" type="button" onclick="generarVenta.getFormNewIngresoDirecto(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo VGEVE_36;?>
                </button>
                    <?php else: ?> 
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta" type="button" disabled class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo VGEVE_35;?>
                </button>   
                <button id="<?php echo VGEVE; ?>btnNewRegGenerarVenta2" type="button" disabled class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo VGEVE_36;?>
                </button>
                    <?php endif; ?> 
                <?php endif; ?>                
            </div>
        </div>

    </div>
    <table id="<?php echo VGEVE; ?>gridGenerarVenta" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($pagar["permiso"]): ?>
                    <button type="button" class="<?php echo $pagar['theme']; ?> margin-top-5" title="<?php echo $pagar['accion']; ?>" ><i class="<?php echo $pagar['icono'];?>"></i>  <?php echo VGEVE_32; ?>  </button>                                        
                    <?php endif;?>                                         
                    <?php if($exportarpdf["permiso"]): ?>
                    <button type="button" class="<?php echo $exportarpdf['theme']; ?> margin-top-5" title="<?php echo $exportarpdf['accion']; ?>" ><i class="<?php echo $exportarpdf['icono'];?>"></i>  <?php echo $exportarpdf['accion']; ?>  </button>                                        
                    <?php endif;?>                                         
                     <?php if($exportarexcel["permiso"]): ?>
                    <button type="button" class="<?php echo $exportarexcel['theme']; ?> margin-top-5" title="<?php echo $exportarexcel['accion']; ?>" ><i class="<?php echo $exportarexcel['icono'];?>"></i>  <?php echo $exportarexcel['accion']; ?>  </button>                                        
                    <?php endif;?>                                                                                                    
                    <?php if($anular["permiso"]): ?>
                    <button type="button" class="<?php echo $anular['theme']; ?> margin-top-5" title="<?php echo $anular['accion']; ?>" ><i class="<?php echo $anular['icono'];?>"></i>  <?php echo $anular['accion']; ?>  </button>                                        
                    <?php endif;?>    
                    <?php if($editar["permiso"]): ?>
                    <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?>  </button>                                        
                    <?php endif;?> 
                </div>
            </div>
        </section>
    </div>
<?php echo Functions::widgetClose(); ?>
<script>
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VGEVE; ?>txt_f1',
        fin: '#<?php echo VGEVE; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VGEVE; ?>txt_f2',
        fin: '#<?php echo VGEVE; ?>txt_f1',
        opt: 'maxDate'
    });
    
    simpleScript.setEvent.blur({   
            element: '#<?php echo VGEVE; ?>txt_f1, #<?php echo VGEVE; ?>txt_f2',
            event: function(){      
                generarVenta.getGridGenerarVenta();
            }
    });  
    
    simpleScript.setEvent.change({   
            element: '#<?php echo VGEVE; ?>txt_f1, #<?php echo VGEVE; ?>txt_f2',
            event: function(){      
                generarVenta.getGridGenerarVenta();
            }
    });   
    
</script>