<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-05-2016 18:05:40 
* Descripcion : indexReporteBeneficiario.phtml
* ---------------------------------------
*/
$pdf   = Session::getPermiso('VRPT7EP');
$excel = Session::getPermiso('VRPT7EX');

if( Session::get('sys_visible') == 'S' ){
    $idSucursal = 1; // Administrador por defecto 1. Ya al seleccionar el combo se mostrara los demas cajas x sucursal.
}else{
    $idSucursal = Session::get('sys_idSucursal'); // Sucursal configurada desde usuarios para el cajero.
}
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VRPT7,
        "title"=>"ReporteBeneficiario",
        "actions" => array( 
                array(
                    'id' => VRPT7 . 'btnPDF',                    
                    'permiso'=> 'VRPT7EP',
                    'click' => 'reporteBeneficiario.postPDFGeneral();'                    
                ),
                array(
                    'id' => VRPT7 . 'btnExcel',                    
                    'permiso'=> 'VRPT7EX',
                    'click' => 'reporteBeneficiario.postExcelGeneral();'                    
                ),
                array(
                    "id" => VRPT7 . "gridReporteBeneficiario_btnRecarga",                    
                    "permiso"=> "VRPT7REC",
                    "click" => "reporteBeneficiario.getGridReporteBeneficiario();"                  
                )
            )
    )); 
?>
<button id="<?php echo VRPT7; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VRPT7; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:0px;top:5px; width: 90%">      
          <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-2 " style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VRPT7.'lst_sucursalGrid',
                                'name'=>VRPT7.'lst_sucursalGrid',   
                                'onchange'=>'vegresos.getBeneficiario({
                                            idSucursal: $(\'#'.VRPT7.'lst_sucursalGrid\').val(),
                                            content: \'#'.VRPT7.'cont-beneficiario\',
                                            idElement: \''.VRPT7.'lst_beneficiario\',
                                            nameElement: \''.VRPT7.'lst_beneficiario\',                                                     
                                            onchange: \'reporteBeneficiario.getGridReporteBeneficiario();\'   
                                        }); reporteBeneficiario.getGridReporteBeneficiario();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false,
                            'encript' => true
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
        <label class="label col col-1"><?php echo VEGRE_6; ?>  </label>
        <div class="col col-3">
              <label class="select" id="<?php echo VRPT7; ?>cont-beneficiario"> 
                 <?php
                     $dataBeneficiario = vegresosController::getFindDataBeneficiarioAll($idSucursal);
                         echo Functions::selectHtml(array(
                             'data'=>$dataBeneficiario,
                             'atributes'=>array(
                                 'id'=>VRPT7.'lst_beneficiario',
                                 'name'=>VRPT7.'lst_beneficiario',     
                                 'onchange'=>'reporteBeneficiario.getGridReporteBeneficiario();'
                             ),  
                             'etiqueta'=> 'persona',
                             'value'=>'id_persona',
                             'group'=>'tipo',
                             'defaultEtiqueta'=>'',
                             'txtSelect'=>true,
                             'encript' => true
                     ));
                  ?>                               
              </label>                                                                                           
        </div>
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-2" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VRPT7;?>txt_f1" name="<?php echo CAJAA;?>txt_f1" value ="<?php echo date("01/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VGEVE; ?>gridReporteBeneficiario_btnRecarga',event);" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-2" style="padding-left:10px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VRPT7;?>txt_f2" name="<?php echo CAJAA;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VGEVE; ?>gridReporteBeneficiario_btnRecarga',event);" />
             </div>            
        </div>      
    </div>      
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->                
            </div>
        </div>

    </div>    
    <table id="<?php echo VRPT7; ?>gridReporteBeneficiario" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
     

<?php echo Functions::widgetClose(); ?>
<script>
    simpleScript.chosen({'id':'#<?php echo VRPT7; ?>lst_beneficiario'});
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VRPT7; ?>txt_f1',
        fin: '#<?php echo VRPT7; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VRPT7; ?>txt_f2',
        fin: '#<?php echo VRPT7; ?>txt_f1',
        opt: 'maxDate'
    });
    
    simpleScript.setEvent.blur({   
            element: '#<?php echo VRPT7; ?>txt_f1, #<?php echo VRPT7; ?>txt_f2',
            event: function(){      
                reporteBeneficiario.getGridReporteBeneficiario();
            }
    });  
    
    simpleScript.setEvent.change({   
            element: '#<?php echo VRPT7; ?>txt_f1, #<?php echo VRPT7; ?>txt_f2',
            event: function(){      
                reporteBeneficiario.getGridReporteBeneficiario();
            }
    });   
    
    
    
</script>