<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 22-11-2014 20:11:18 
* Descripcion : indexVegresos.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VEGRENEW");
$anular = Session::getPermiso("VEGREAN");
$editar = Session::getPermiso("VEGREED");
$recargar = Session::getPermiso("VEGREREC");

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VEGRE,
        "title"=>VEGRE_1,
        'actions' => array(               
                array(
                    'id' => VEGRE . 'gridVegresos_btnRecarga',                    
                    'permiso'=> 'VEGREREC',
                    'click' => 'vegresos.getGridVegresos();'                    
                )
            )
    )); 

if( Session::get('sys_visible') == 'N' ){
    $validarCaja = cajaAperturaController::getValidarCaja()['existe'];    
}else{
    $validarCaja = 1;
}

?>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:250px;top:5px; width: 50%">               
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VEGRE;?>txt_f1" name="<?php echo CAJAA;?>txt_f1" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VEGRE; ?>gridVegresos_btnRecarga',event);" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-3" style="padding-left:10px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VEGRE;?>txt_f2" name="<?php echo CAJAA;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo VEGRE; ?>gridVegresos_btnRecarga',event);"/>
             </div>            
        </div>
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-3" style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VEGRE.'lst_sucursalGrid',
                                'name'=>VEGRE.'lst_sucursalGrid',   
                                'onchange'=>'vegresos.getGridVegresos();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>         
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                    <?php if($validarCaja > 0 ): ?>
                <button id="<?php echo VEGRE; ?>btnNewVegresos" type="button" onclick="vegresos.getFormNewVegresos(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button> 
                    <?php else: ?>
                <button id="<?php echo VEGRE; ?>btnNewVegresos" type="button" disabled class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button> 
                    <?php endif; ?>
                <?php endif; ?>                
            </div>
        </div>

    </div>    
    <table id="<?php echo VEGRE; ?>gridVegresos" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">     
                    <?php if($editar["permiso"]): ?>
                    <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?>  </button>                                        
                    <?php endif;?>   
                    <?php if($anular["permiso"]): ?>
                    <button type="button" class="<?php echo $anular['theme']; ?> margin-top-5" title="<?php echo $anular['accion']; ?>" ><i class="<?php echo $anular['icono'];?>"></i>  <?php echo $anular['accion']; ?>  </button>                                        
                    <?php endif;?>                    
                </div>
            </div>
        </section>
    </div>
<?php echo Functions::widgetClose(); ?>
<script>
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VEGRE; ?>txt_f1',
        fin: '#<?php echo VEGRE; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VEGRE; ?>txt_f2',
        fin: '#<?php echo VEGRE; ?>txt_f1',
        opt: 'maxDate'
    });
    
    simpleScript.setEvent.blur({   
            element: '#<?php echo VEGRE; ?>txt_f1, #<?php echo VEGRE; ?>txt_f2',
            event: function(){      
                vegresos.getGridVegresos();
            }
    });  
    
    simpleScript.setEvent.change({   
            element: '#<?php echo VEGRE; ?>txt_f1, #<?php echo VEGRE; ?>txt_f2',
            event: function(){      
                vegresos.getGridVegresos();
            }
    });   
    
    
    
</script>