<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 10-05-2016 19:05:57 
* Descripcion : indexModificarVenta.phtml
* ---------------------------------------
*/
$editar   = Session::getPermiso('VMOVEMOD');
$quitar = Session::getPermiso('VMOVECAN');
$exportarpdf   = Session::getPermiso('VMOVEEP');

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VMOVE,
        "title"=>VMOVE_01,
        "actions" => array(               
                array(
                    "id" => VMOVE . "gridModificarVenta_btnRecarga",                    
                    "permiso"=> "VMOVEREC",
                    "click" => "modificarVenta.getGridModificarVenta();"                  
                )
            )
    )); 
?>
<button id="<?php echo VMOVE; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VMOVE; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
     <div class="smart-form" style="position: absolute;left:300px;top:5px; width: 50%">                       
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <div class="col col-3" style="padding-left:10px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VMOVE.'lst_sucursalGrid',
                                'name'=>VMOVE.'lst_sucursalGrid',   
                                'onchange'=>'vseguimientoventa.getGridVseguimientoventa();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>      
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">                    
            </div>
        </div>

    </div>    
    <table id="<?php echo VMOVE; ?>gridModificarVenta" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
        
 <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($exportarpdf["permiso"]): ?>
                    <button type="button" class="<?php echo $exportarpdf['theme']; ?> margin-top-5" title="<?php echo $exportarpdf['accion']; ?>" ><i class="<?php echo $exportarpdf['icono'];?>"></i>  <?php echo  $exportarpdf['accion']; ?>  </button>                                        
                    <?php endif;?>    
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar["theme"]; ?> margin-top-5" title="<?php echo $editar["accion"]; ?>" ><i class="<?php echo $editar["icono"];?>"></i>  <?php echo $editar["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                    <?php if($quitar["permiso"]): ?>
                        <button type="button" class="<?php echo $quitar["theme"]; ?> margin-top-5" title="<?php echo $quitar["accion"]; ?>" ><i class="<?php echo $quitar["icono"];?>"></i>  <?php echo $quitar["accion"]; ?> </button>                    
                    <?php endif;?>       
                </div>
            </div>

        </section>
    </div>

<?php echo Functions::widgetClose(); ?>