<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-12-2014 21:12:27 
* Descripcion : indexCajaApertura.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("CAJAANEW");
$recargar   = Session::getPermiso('CAJAAREC');
$editar    = Session::getPermiso("CAJAAED");

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>CAJAA,
        "title"=>CAJAA_1,
        'overflow'=> 'none',
        'actions' => array(               
                array(
                    'id' => CAJAA . 'gridCajaApertura_btnRecarga',                    
                    'permiso'=> 'CAJAAREC',
                    'click' => 'cajaApertura.getGridCajaApertura();'                    
                )
            )
    )); 
?>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:0;top:5px;width: 65%">               
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAA;?>txt_f1" name="<?php echo CAJAA;?>txt_f1" value ="01/<?php echo date("m"); ?>/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo CAJAA; ?>gridCajaApertura_btnRecarga',event);" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAA;?>txt_f2" name="<?php echo CAJAA;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo CAJAA; ?>gridCajaApertura_btnRecarga',event);" />
             </div>            
        </div>
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <label class="label col col-1 font-xs">&nbsp;<?php echo VGEVE_15; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>CAJAA.'lst_sucursalGrid',
                                'name'=>CAJAA.'lst_sucursalGrid',   
                                'onchange'=>'cajaApertura.getGridCajaApertura();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>        
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                  <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo CAJAA; ?>btnNewCajaApertura" type="button" onclick="cajaApertura.getFormNewCajaApertura(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>                                
            </div>
        </div>

    </div>
    <table id="<?php echo CAJAA; ?>gridCajaApertura" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    <div class="modal-body smart-form"  style="padding: 0 0 0 10px;"  >
        <section>
           <div class="row">
               <label class="label col col-2">
               <?php echo LABEL_LEYENDA; ?>
               </label>
               <div class="col col-9 ">                            
                   <?php if($editar["permiso"]): ?>
                   <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?> </button>                    
                   <?php endif;?>                           
               </div>
           </div>
       </section>    
   </div>   
    
<?php echo Functions::widgetClose(); ?>
<script>

    simpleScript.setEvent.dateRange({
        ini: '#<?php echo CAJAA; ?>txt_f1',
        fin: '#<?php echo CAJAA; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo CAJAA; ?>txt_f2',
        fin: '#<?php echo CAJAA; ?>txt_f1',
        opt: 'maxDate'
    });
    
    simpleScript.setEvent.blur({   
            element: '#<?php echo CAJAA; ?>txt_f1, #<?php echo CAJAA; ?>txt_f2',
            event: function(){      
                cajaApertura.getGridCajaApertura();
            }
    });  
    
    simpleScript.setEvent.change({   
            element: '#<?php echo CAJAA; ?>txt_f1, #<?php echo CAJAA; ?>txt_f2',
            event: function(){      
                cajaApertura.getGridCajaApertura();
            }
    });   
    
</script>