<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 14-11-2014 09:50:58 
* Descripcion : indexVGenerarCotizacion.phtml
* ---------------------------------------
*/
$nuevo   = Session::getPermiso("VCOTINEW");
$anular = Session::getPermiso("VCOTIAN");
$exportarpdf   = Session::getPermiso('VCOTIEP');
$exportarexcel = Session::getPermiso('VCOTIEX');
$enviaremail   = Session::getPermiso('VCOTIEE');
$generar   = Session::getPermiso('VCOTIGN');
$recargar = Session::getPermiso("VCOTIREC");
$clonar   = Session::getPermiso('VCOTICL');
$migrar  = Session::getPermiso("VCOTIMIGR");

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>VCOTI,
        "title"=>VCOTI_1,
        'actions' => array(               
                array(
                    'id' => VCOTI . 'gridVGenerarCotizacion_btnRecarga',                    
                    'permiso'=> 'VCOTIREC',
                    'click' => 'vGenerarCotizacion.getGridVGenerarCotizacion();'                    
                )
            )
    )); 
?>
<button id="<?php echo VCOTI; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VCOTI; ?>btnDowExcel" type="button" class="hide">Descargar</button>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo VCOTI; ?>btnNewRegVGenerarCotizacion" type="button" onclick="vGenerarCotizacion.getFormNewVGenerarCotizacion(this);" class="<?php echo $nuevo['theme'];?>">
                    <i class="<?php echo $nuevo['icono'];?>"></i> <?php echo $nuevo['accion'];?>
                </button>
                <?php endif; ?>                
            </div>
        </div>

    </div>
    
    <table id="<?php echo VCOTI; ?>gridVGenerarCotizacion" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">                      
                    <?php if($exportarpdf["permiso"]): ?>
                    <button type="button" class="<?php echo $exportarpdf['theme']; ?> margin-top-5" title="<?php echo $exportarpdf['accion']; ?>" ><i class="<?php echo $exportarpdf['icono'];?>"></i>  <?php echo VCOTI_3; ?>  </button>                                        
                    <?php endif;?>                                         
                     <?php if($exportarexcel["permiso"]): ?>
                    <button type="button" class="<?php echo $exportarexcel['theme']; ?> margin-top-5" title="<?php echo $exportarexcel['accion']; ?>" ><i class="<?php echo $exportarexcel['icono'];?>"></i>  <?php echo $exportarexcel['accion']; ?>  </button>                                        
                    <?php endif;?>                                         
                     <?php if($enviaremail["permiso"]): ?>
                    <button type="button" class="<?php echo $enviaremail['theme']; ?> margin-top-5" title="<?php echo $enviaremail['accion']; ?>" ><i class="<?php echo $enviaremail['icono'];?>"></i>  <?php echo $enviaremail['accion']; ?>  </button>                                        
                    <?php endif;?>     
                    <?php if($clonar["permiso"]): ?>
                    <button type="button" class="<?php echo $clonar['theme']; ?> margin-top-5" title="<?php echo $clonar|['accion']; ?>" ><i class="<?php echo $clonar['icono'];?>"></i>  <?php echo $clonar['accion']; ?></button>                                        
                    <?php endif;?>  
                    <?php if($migrar["permiso"]): ?>
                    <button type="button" class="<?php echo $migrar['theme']; ?> margin-top-5" title="<?php echo $migrar|['accion']; ?>" ><i class="<?php echo $migrar['icono'];?>"></i>  <?php echo $migrar['accion']; ?></button>                                        
                    <?php endif;?>  
                    <?php if($generar["permiso"]): ?>
                    <button type="button" class="<?php echo $generar['theme']; ?> margin-top-5" title="<?php echo $generar['accion']; ?>" ><i class="<?php echo $generar['icono'];?>"></i>  <?php echo $generar['accion']; ?> Venta </button>                                        
                    <?php endif;?>   
                    <?php if($anular["permiso"]): ?>
                    <button type="button" class="<?php echo $anular['theme']; ?> margin-top-5" title="<?php echo $anular['accion']; ?>" ><i class="<?php echo $anular['icono'];?>"></i>  <?php echo $anular['accion']; ?>  </button>                                        
                    <?php endif;?>                                         
                </div>
            </div>
        </section>
    </div>
<?php echo Functions::widgetClose(); ?>