<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-11-2014 00:11:17 
* Descripcion : indexReporteVentaFecha.phtml
* ---------------------------------------
*/
$exportarpdf   = Session::getPermiso('VRPT2EP');
$exportarexcel = Session::getPermiso('VRPT2EX');

echo Functions::widgetOpen(array(
        "id"=>VRPT2,
        "title"=>VRPT2_1,
        'actions' => array(               
                array(
                    'id' => VRPT2 . 'gridReporteVentaFecha_btnRecarga',                    
                    'permiso'=> 'VRPT2REC',
                    'click' => 'reporteVentaFecha.getGridReporteVentaFecha();'                    
                )
            )
    )); 
?>
<button id="<?php echo VRPT2; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo VRPT2; ?>btnDowExcel" type="button" class="hide">Descargar</button>
<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:0;top:5px;width: 65%">               
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VRPT2;?>txt_f1" name="<?php echo VRPT2;?>txt_f1" value ="01/<?php echo date("m"); ?>/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " onchange="reporteVentaFecha.getGridReporteVentaFecha();" onblur="reporteVentaFecha.getGridReporteVentaFecha();" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo VRPT2;?>txt_f2" name="<?php echo VRPT2;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onchange="reporteVentaFecha.getGridReporteVentaFecha();" onblur="reporteVentaFecha.getGridReporteVentaFecha();" />
             </div>            
        </div>
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <label class="label col col-1 font-xs">&nbsp;<?php echo VGEVE_15; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>VRPT2.'lst_sucursalGrid',
                                'name'=>VRPT2.'lst_sucursalGrid',   
                                'onchange'=>'cajaCierre.getGridCajaCierre();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>      
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
               
            </div>
        </div>
    </div>
        <table id="<?php echo VRPT2; ?>gridReporteVentaFecha" class="table table-striped table-hover table-condensed" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>
<script>

    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VRPT2; ?>txt_f1',
        fin: '#<?php echo VRPT2; ?>txt_f2',
        opt: 'minDate'
    });
    
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VRPT2; ?>txt_f2',
        fin: '#<?php echo VRPT2; ?>txt_f1',
        opt: 'maxDate'
    });       
    
</script>