<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 06-12-2014 23:12:35 
* Descripcion : indexCajaCierre.phtml
* ---------------------------------------
*/

$recargar   = Session::getPermiso('CAJACREC');
$generar    = Session::getPermiso("CAJACGN");
$exportarpdf   = Session::getPermiso('CAJACEP');
$exportarexcel = Session::getPermiso('CAJACEX');

echo Functions::widgetOpen(array(
        "id"=>CAJAC,
        "title"=>CAJAC_1,
        'overflow'=> 'none',
        'actions' => array(               
                array(
                    'id' => CAJAC . 'gridCajaCierre_btnRecarga',                    
                    'permiso'=> 'CAJACREC',
                    'click' => 'cajaCierre.getGridCajaCierre();'                    
                )
            )
    )); 
?>
<button id="<?php echo CAJAC; ?>btnDowPDF" type="button" class="hide">Descargar</button>
<button id="<?php echo CAJAC; ?>btnDowExcel" type="button" class="hide">Descargar</button>

<div class="widget-body-toolbar">
    <div class="smart-form" style="position: absolute;left:0;top:5px;width: 65%">               
        <label class="label col col-1 font-xs"><?php echo LABEL_DESDE; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAC;?>txt_f1" name="<?php echo CAJAC;?>txt_f1" value ="01/<?php echo date("m"); ?>/<?php echo date("Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo CAJAC; ?>gridCajaCierre_btnRecarga',event);" />
             </div>            
        </div>
        <label class="label col col-1 font-xs">&nbsp;<?php echo LABEL_HASTA; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <input class="form-control" type="text" id="<?php echo CAJAC;?>txt_f2" name="<?php echo CAJAC;?>txt_f2" value ="<?php echo date("d/m/Y"); ?>" style="padding-left:10px; width: 80px; " onkeypress="simpleScript.triggerPress('#<?php echo CAJAC; ?>gridCajaCierre_btnRecarga',event);" />
             </div>            
        </div>
        <?php  if( Session::get('sys_visible') == 'S' ): ?>  
        <label class="label col col-1 font-xs">&nbsp;<?php echo VGEVE_15; ?></label>        
        <div class="col col-3" style="padding-left:20px;">
            <label class="select"> 
                <?php
                    $dataSucursal = vSucursalController::getSucursalSiglaAll();
                        echo Functions::selectHtml(array(
                            'data'=>$dataSucursal,
                            'atributes'=>array(
                                'id'=>CAJAC.'lst_sucursalGrid',
                                'name'=>CAJAC.'lst_sucursalGrid',   
                                'onchange'=>'cajaCierre.getGridCajaCierre();'
                            ),  
                            'etiqueta'=>'sigla',
                            'value'=>'id',
                            'defaultEtiqueta'=>'1',
                            'txtSelect'=>false                                           
                    ));
               ?><i></i>                                  
             </label>  
        </div>
        <?php endif; ?>
    </div>              
</div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">

            </div>
        </div>

    </div>
    <table id="<?php echo CAJAC; ?>gridCajaCierre" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    <div class="modal-body smart-form"  style="padding: 0 0 0 10px;"  >
        <section>
           <div class="row">
               <label class="label col col-2">
               <?php echo LABEL_LEYENDA; ?>
               </label>
               <div class="col col-9 ">                            
                   <?php if($generar["permiso"]): ?>
                   <button type="button" class="<?php echo $generar['theme']; ?> margin-top-5" title="<?php echo $generar['accion']; ?>" ><i class="<?php echo $generar['icono'];?>"></i>  <?php echo $generar['accion'].' '.LABEL_CIERRE; ?> </button>                    
                   <?php endif;?>  
                   <?php if($reajustar["permiso"]): ?>
                   <button type="button" class="<?php echo $reajustar['theme']; ?> margin-top-5" title="<?php echo $reajustar['accion']; ?>" ><i class="<?php echo $reajustar['icono'];?>"></i>  <?php echo $reajustar['accion']; ?> </button>                    
                   <?php endif;?>
                   <?php if($exportarpdf["permiso"]): ?>
                   <button type="button" class="<?php echo $exportarpdf['theme']; ?> margin-top-5" title="<?php echo $exportarpdf['accion']; ?>" ><i class="<?php echo $exportarpdf['icono'];?>"></i>  <?php echo $exportarpdf['accion']; ?>  </button>                                        
                   <?php endif;?>                                         
                    <?php if($exportarexcel["permiso"]): ?>
                   <button type="button" class="<?php echo $exportarexcel['theme']; ?> margin-top-5" title="<?php echo $exportarexcel['accion']; ?>" ><i class="<?php echo $exportarexcel['icono'];?>"></i>  <?php echo $exportarexcel['accion']; ?>  </button>                                        
                   <?php endif;?>     
               </div>
           </div>
       </section>    
   </div>
    
<?php echo Functions::widgetClose(); ?>
<script>

    simpleScript.setEvent.dateRange({
        ini: '#<?php echo CAJAC; ?>txt_f1',
        fin: '#<?php echo CAJAC; ?>txt_f2',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo CAJAC; ?>txt_f2',
        fin: '#<?php echo CAJAC; ?>txt_f1',
        opt: 'maxDate'
    });
    
    simpleScript.setEvent.blur({   
            element: '#<?php echo CAJAC; ?>txt_f1, #<?php echo CAJAC; ?>txt_f2',
            event: function(){      
                cajaCierre.getGridCajaCierre();
            }
    });  
    
    simpleScript.setEvent.change({   
            element: '#<?php echo CAJAC; ?>txt_f1, #<?php echo CAJAC; ?>txt_f2',
            event: function(){      
               cajaCierre.getGridCajaCierre();
            }
    });   
    
</script>