<?php
/*
 * Documento   : lock
 * Creado      : 17-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
?>
<form id="clave-form" class="lockscreen animated flipInY" onsubmit="return false;">
    <img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt="" width="auto" height="60" />
    <div class="logo">
        <!--<h1 class="semi-bold"><img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt=""/> Simple ERP</h1>-->
    </div>
    <div>
        <?php 
        $data = Obj::run()->indexModel->getFoto();
                if ($data['foto'] == '' || $data['foto'] == null) {
                        if ($this->sexo === 'H'): /*Hombre*/
                            $imagen = $rutaLayout["_img"] . 'avatars/male.png';
                        elseif ($this->sexo === 'M'): /*Mujer*/
                            $imagen = $rutaLayout["_img"] . 'avatars/female.png';
                        else :
                            $imagen = $rutaLayout["_img"] . 'avatars/user_anonimus.png';
                        endif;                                               
                    } else {
                        $imagen = BASE_URL . 'public/img/fotos/' . $data['foto'];
                    }
                
                ?>
        <img src="<?php echo $imagen;?>" alt="" width="120" height="120"/>
        <div>
            <h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile" style="z-index: 0"></i>
                <?php echo $this->nameUsuario; ?> <small><i class="fa fa-lock text-muted"></i> &nbsp;<?php echo LABEL_CLAVEADMIN; ?></small></h1>
<!--            <p class="text-muted">
                el correo
            </p>-->

            <div class="input-group">                                                     
                <input type="hidden" name="txtUser" id="txtUser" value="<?php echo $this->usuario ?>">
                <input class="form-control" type="password" placeholder="Contraseña" id="txtClaveAdmin" autocomplete="off" name="txtClaveAdmin" value="">
                <div class="input-group-btn" style="z-index: 1">
                    <button id="btnEntrar" class="btn btn-primary" type="submit">
                        <i class="fa fa-key"></i> <?php echo L_TITLE; ?>
                    </button>
                </div>                                                                     
            </div>
            <p class="no-margin margin-top-5">
              <a href="javascript:index.postLogout()">  <?php echo '¿'.INDEX_CERRARSESION.'?'.' '.LABEL_CLICKAQUI; ?> </a>
            </p>
        </div>

    </div>
    <p class="font-xs margin-top-5">
        <?php echo COPY; ?>
    </p>
</form>
<script>   
    var noneEvtMenu = function(){};
//    setTimeout(function(){
//        $('.modal-backdrop').css('z-index', -1);
//    }, 0);
    
    setTimeout(function(){
         loginScript.validateAdmin();
     },1000);
    
</script>