<?php
$doc = $data = Obj::run()->indexModel->getFoto();
$fileActual = $doc['foto'];

?>
<div id="<?php echo INDEX; ?>formChangeFoto" name="<?php echo INDEX; ?>formChangeFoto" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Subir Foto</h4>
            </div>
            <div class="modal-body smart-form">
                <form class="dropzone" id="mydropzone">
                    <input type="hidden" id="<?php echo INDEX; ?>_file" name="<?php echo INDEX; ?>_file" value="<?php echo $fileActual; ?>">
                </form>
                <?php if(sizeof($doc) && isset($doc['foto']) && $doc['foto'] !== '' ):?>
                <a id="<?php echo INDEX; ?>dow" href="javascript:;" onclick="index.getFormViewFoto('<?php echo AesCtr::en(BASE_URL.'public/img/fotos/'.$doc['foto']); ?>');"><?php echo $doc['foto'];?></a>
                <button id="<?php echo INDEX; ?>btndow" type="button" class="btn btn-danger pull-right" style="padding: 5px" onclick="index.deleteImagen(this,'<?php echo 'public/img/fotos/'.$doc['foto']; ?>');"><i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?></button>
                <?php else: ?>
                <a id="<?php echo INDEX; ?>dow" href="javascript:;">&nbsp;</a><button id="<?php echo INDEX; ?>btndow" type="button" class="btn btn-danger pull-right" style="padding: 5px; display: none;"><i class="fa fa-trash-o"></i> <?php echo BTN_DELETE; ?></button>
                <?php endif; ?>
            </div>
            <div class="modal-footer">
               <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?> 
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

   
    <script>
        Dropzone.autoDiscover = false;
        $("#mydropzone").dropzone({
            acceptedFiles: ".png, .jpg, .JPG, .PNG, .JPEG, .jpeg",
            url: '<?php echo BASE_URL; ?>index/index/postFoto',
            maxFiles: 1, // Number of files at a time
            maxFilesize: 10, //in MB
            addRemoveLinks: true,
            dictResponseError: 'Error uploading file!',
            dictDefaultMessage: 'Arrastre aquí una imagen',
             maxfilesexceeded: function(f){
                 simpleScript.notify.error({
                        content: 'Usted ha subido más de 1 imagen. Sólo el primer archivo se cargará!'
                 });
            },
            complete: function(data){
                 if (data.xhr != undefined){
                    var json = JSON.parse(data.xhr.responseText);   
                    var file = "public/img/fotos/"+json.archivo;                    
                    var fileEncriptado = simpleAjax.stringPost('public/img/fotos/'+json.archivo);
                    
                    $('#<?php echo INDEX; ?>dow').attr('onclick',"index.getFormViewFoto('"+fileEncriptado+"');");
                    $('#<?php echo INDEX; ?>dow').html(json.archivo); 
                    $('#<?php echo INDEX; ?>btndow').attr('onclick',"index.deleteImagen(this,'"+file+"');");
                    $('#<?php echo INDEX; ?>btndow').css('display','block');                    
                    $('#<?php echo INDEX; ?>_file').val(json.archivo);         
                    
                    //Actualizo Imagen de index:
                    $('#fotitoUser').attr("src",file);
                    
                }
            }
        });
    </script>
</div>
