<?php
/*
 * Documento   : lock
 * Creado      : 17-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
?>
<form id="login-form" class="lockscreen animated flipInY" onsubmit="return false;">
    <img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt="" width="auto" height="60" />
    <div class="logo">
        <!--<h1 class="semi-bold"><img src="<?php echo $rutaLayout['_img']; ?>logo.png" alt=""/> Simple ERP</h1>-->
    </div>
    <div>
        <?php 
        $data = Obj::run()->indexModel->getFoto();
                if ($data['foto'] == '' || $data['foto'] == null) {
                        if ($this->sexo === 'H'): /*Hombre*/
                            $imagen = $rutaLayout["_img"] . 'avatars/male.png';
                        elseif ($this->sexo === 'M'): /*Mujer*/
                            $imagen = $rutaLayout["_img"] . 'avatars/female.png';
                        else :
                            $imagen = $rutaLayout["_img"] . 'avatars/user_anonimus.png';
                        endif;                                               
                    } else {
                        $imagen = BASE_URL . 'public/img/fotos/' . $data['foto'];
                    }
                
                ?>
        <img src="<?php echo $imagen;?>" alt="" width="120" height="120"/>
        <div>
            <h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile" style="z-index: 0"></i>
                <?php echo $this->nameUsuario; ?> <small><i class="fa fa-lock text-muted"></i> &nbsp;<?php echo LABEL_BLOQUEADO; ?></small></h1>
<!--            <p class="text-muted">
                el correo
            </p>-->

            <div class="input-group">
                <?php if(isset($this->tipoAcceso)):
                        switch ($this->tipoAcceso):
                            case 'N': ?>                                                        
                                <input type="hidden" name="txtUser" id="txtUser" value="<?php echo $this->usuario ?>">
                                <input class="form-control" type="password" placeholder="Contraseña" id="txtClave" name="txtClave" value="">
                                <div class="input-group-btn" style="z-index: 1">
                                    <button id="btnEntrar" class="btn btn-primary" type="submit">
                                        <i class="fa fa-key"></i> <?php echo LABEL_DESBLOQUEAR; ?>
                                    </button>
                                </div>                                
                <?php           break;
                           case 'F': ?>   
                            <section>
                                <a href="<?php echo $helper->getLoginUrl($config['scopes']); ?>" class="btn btn-primary padding-10 "> 
                                   <i class="fa fa-facebook-official"></i> <?php echo L_L_FACEBOOK; ?>
                                </a>
                            </section>
                <?php       break;
                        endswitch;
                    ?>                                                                        
                <?php endif;  ?>                                
            </div>
            <p class="no-margin margin-top-5">
                <?php echo LABEL_OTRAPERSONA; ?> <a href="index"> <?php echo LABEL_CLICKAQUI; ?></a>
            </p>
        </div>

    </div>
    <p class="font-xs margin-top-5">
        <?php echo COPY; ?>
    </p>
</form>
<script>
    loginScript.validate();
    setTimeout(function(){
        $('.modal-backdrop').css('z-index', -1);
    }, 0);
</script>