<?php 
$nuevo = Session::getPermiso('ACCGR');

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        'id'=>T2.'acciones',
        'title'=>'Acciones',
        'actions' => array(               
                array(
                    'id' => T2 . 'gridAcciones_btnRecarga',                    
                    'permiso'=> 'ACCREC',
                    'click' => 'acciones.getGridAcciones();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T2; ?>btnNew" class="<?php echo $nuevo['theme']; ?>" onclick="acciones.getFormNuevaAccion()"><i class="<?php echo $nuevo['icono']; ?>"></i> <?php echo BTN_NUEVO; ?></button>
                <?php endif; ?>                
            </div>
        </div>
    </div>

    <table id="<?php echo T2; ?>gridAcciones" class="table table-striped table-hover has-tickbox" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>