<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 23-12-2014 14:12:17 
* Descripcion : formFileIdiomas.phtml
* ---------------------------------------
*/

/*prefijo: IDIOM debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("IDIOMACT");
$data = idiomasController::findIdiomas();

$fn1 = 'lang/lang_'.$data['sigla'].'.php';
$fn2 = 'lang/js/lang_'.$data['sigla'].'.js';

$fn11 = '../lang/lang_'.$data['sigla'].'.php';
$fn22 = '../lang/js/lang_'.$data['sigla'].'.js';

?>
<form id="<?php echo IDIOM; ?>formFileIdiomas" name="<?php echo IDIOM; ?>formFileIdiomas" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:70%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo IDIOM_09; ?></h4>
            </div>
            
            <div class="modal-body smart-form scroll-form" style="height: auto;"  >
                <ul class="nav nav-tabs bordered">
                    <li class="active">
                        <a id="tab1" href="#s1" data-toggle="tab"><?php echo LABEL_IDIOMA1; ?></a>                        
                    </li>                   
                    <li>
                        <a id="tab2" href="#s2" data-toggle="tab"><?php echo LABEL_IDIOMA2; ?></a>
                    </li>
                </ul>
                <div class="tab-content padding-10"> 
                     <!-- 1er Tab-->
                     <div class="tab-pane fade in active" id="s1" >                        
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo IDIOM_10; ?></label>
                                <div class="col col-10">
                                    <label class="textarea">
                                        <textarea id="<?php echo IDIOM; ?>txt_archivophp" name="<?php echo IDIOM; ?>txt_archivophp" style="height:200px;" ><?php readfile($fn1);?></textarea>                                
                                    </label>
                                </div>                       
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo IDIOM_11; ?></label>
                                <div class="col col-10">
                                    <label class="textarea">
                                        <textarea id="<?php echo IDIOM; ?>txt_archivojs" name="<?php echo IDIOM; ?>txt_archivojs" style="height:200px;" ><?php readfile($fn2);?></textarea>                                
                                    </label>
                                </div>                       
                            </div>
                        </section> 
                    </div>                     
                    <!-- 2do Tab-->
                    <div class="tab-pane fade" id="s2" >                        
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo IDIOM_10; ?></label>
                                <div class="col col-10">
                                    <label class="textarea">
                                        <textarea id="<?php echo IDIOM; ?>txt_archivophp2" name="<?php echo IDIOM; ?>txt_archivophp2" style="height:200px;" ><?php readfile($fn11);?></textarea>                                
                                    </label>
                                </div>                       
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo IDIOM_11; ?></label>
                                <div class="col col-10">
                                    <label class="textarea">
                                        <textarea id="<?php echo IDIOM; ?>txt_archivojs2" name="<?php echo IDIOM; ?>txt_archivojs2" style="height:200px;" ><?php readfile($fn22);?></textarea>                                
                                    </label>
                                </div>                       
                            </div>
                        </section>       
                    </div>                                       
                 </div>
             </div>                                                    
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo IDIOM; ?>btnFileIdiomas" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo IDIOM; ?>formFileIdiomas");
</script>
<?php endif; ?>
<script>
$("#<?php echo IDIOM; ?>formFileIdiomas").validate({
    rules : {
         <?php echo IDIOM; ?>txt_archivophp : {
            required : true
        },<?php echo IDIOM; ?>txt_archivojs : {
            required : true
        },         
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        idiomas.postFileIdiomas();
    }   
});
</script>