<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 09-12-2014 16:12:55 
* Descripcion : formEditMoneda.phtml
* ---------------------------------------
*/

/*prefijo: MOND debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("MONDACT");
    
$data = monedaController::findMoneda();

?>
<form id="<?php echo MOND; ?>formEditMoneda" name="<?php echo MOND; ?>formEditMoneda" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo MOND_02;?></h4>
            </div>
            <div class="modal-body smart-form"> 
              <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo MOND_04; ?></label>
                        <div class="col col-10">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo MOND; ?>txt_descripcion" name="<?php echo MOND; ?>txt_descripcion" value="<?php echo $data['descripcion'];?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo MOND_04M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>             
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo MOND_05; ?></label>
                        <div class="col col-5">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo MOND; ?>txt_sigla" name="<?php echo MOND; ?>txt_sigla" value="<?php echo $data['sigla'];?>" maxlength="10">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo MOND_05M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo MOND; ?>btnEdMoneda" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo MOND; ?>formEditMoneda");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo MOND; ?>formEditMoneda").validate({
    rules : {
      <?php echo MOND; ?>txt_descripcion : {
            required : true,
            minlength: 2
        },
        <?php echo MOND; ?>txt_sigla : {
            required : true
        }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        moneda.postEditMoneda();
    }   
});
</script>