<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 12-09-2014 17:09:13 
* Descripcion : formEditPlantillaDoc.phtml
* ---------------------------------------
*/
/*prefijo: PLTDC debe ser alias en tabla men_menuprincipal*/

echo Functions::widgetOpen(array(
    'id' => PLTDC.'edit',
    'title' => PLTDC_03,
    'overflow'=> 'none'
));
$editar = Session::getPermiso("PLTDCACT");
$data = plantillaDocController::findPlantillaDoc();

?>
<form id="<?php echo PLTDC; ?>formEditPlantillaDoc" name="<?php echo PLTDC; ?>formEditPlantillaDoc"  >
    <div class="row" style="padding:10px;">
        
        <div class="modal-body smart-form" >                        
            <section>
                <div class="row">
                    <label class="label col col-1"><?php echo PLTDC_04; ?></label>
                    <div class="col col-6">
                        <label class="input"> 
                            <i class="icon-append fa fa-keyboard-o"></i>
                            <input maxlength="100" type="text" id="<?php echo PLTDC; ?>txt_nombre" name="<?php echo PLTDC; ?>txt_nombre" value="<?php echo $data['nombre']; ?>">
                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo PLTDC_04M; ?></b>
                        </label>
                    </div>
                    <label class="label col col-1"><?php echo PLTDC_05; ?></label>
                    <div class="col col-4">
                        <label class="input"> 
                            <i class="icon-append fa fa-keyboard-o"></i>
                            <input maxlength="10" type="text" id="<?php echo PLTDC; ?>txt_alias" name="<?php echo PLTDC; ?>txt_alias" value="<?php echo $data['alias']; ?>">
                            <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo PLTDC_05M; ?></b>
                        </label>
                    </div>
                </div>
            </section>  
        </div>            
        <article class="col-sm-12 col-md-12 col-lg-6 sortable-grid ui-sortable" style="width: 100%; ">
<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-colorbutton="false" 
 data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-fullscreenbutton="false" data-widget-sortable="false">				
                            <header><h2><?php echo PLTDC_06; ?></h2></header>
                            <!-- widget div-->
                            <div>
                                    <!-- widget edit box -->
                                    <div class="jarviswidget-editbox">
                                            <!-- This area used as dropdown edit box -->                                                    
                                    </div>
                                    <!-- end widget edit box -->
                                    <!-- widget content -->
                                    <div class="widget-body no-padding">
                                        
                                        <textarea id="<?php echo PLTDC; ?>txt_cuerpo" class="summernote_msj" name="<?php echo PLTDC; ?>txt_cuerpo" ><?php 
                                                $html = str_replace('\\','',$data['cuerpo'] );
                                                echo htmlspecialchars_decode($html,ENT_QUOTES); ?></textarea>                                           											                                            				
                                            <div class="widget-footer smart-form">
                                                <div class="btn-group">
                                                        <!--
                                                        <button class="btn btn-sm btn-primary" type="button">
                                                                <i class="fa fa-times"></i> Cancel
                                                        </button>	
                                                        -->			
                                                </div>				
                                            </div>						
                                    </div>
                                    <!-- end widget content -->
                            </div>
                            <!-- end widget div -->
                    </div>	
        </article>        
        <div class="modal-footer">
            <div class="foot-obligar"></div>
            <?php if($editar["permiso"]):?>
            <button id="<?php echo PLTDC; ?>btnEdPlantillaDoc" type="submit" class="<?php echo $editar["theme"]; ?>">
                <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
            </button>
            <?php endif; ?>
            <button type="button" class="<?php echo THEME_CLOSE; ?>" onclick="simpleScript.closeTab(diccionario.tabs.PLTDC+'edit');" >
                <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
            </button>
        </div>        
    </div><!-- /.modal-dialog -->
</form>

 <?php echo Functions::widgetClose(); ?>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo PLTDC; ?>formEditPlantillaDoc");
</script>
<?php endif; ?>
<script>
    
    pageSetUp();
     var pagefunction = function() {		
            $('.summernote_msj').summernote({
                    height : 300,
                    focus : true,                  
                    lang: 'es-ES',
                    toolbar: [
                    ['style', ['style']],
                    ['font', ['bold','italic' ,'underline', 'clear']],
                    ['fontname', ['fontname','fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link']],
                    ['view', [ 'codeview', 'help']]
                  ]/*fullscreen*/
            });				
    };	
        
    loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/summernote/summernote.min.js", function(){
        loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/summernote/lang/summernote-es-ES.min.js", function(){
            loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/markdown/markdown.min.js", function(){
                            loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/markdown/bootstrap-markdown.min.js", pagefunction);
            });
        });
    });
    
    simpleScript.setEvent.blur({   
            element:'.summernote_msj',
            event: function(){      
                $('textarea[name="content"]').html($('.summernote_msj').summernote('code'));  
            }
    });        

    /*configurar validacion de formulario -- este codigo es de ejemplo*/
    $("#<?php echo PLTDC; ?>formEditPlantillaDoc").validate({
        rules : {
            <?php echo PLTDC; ?>txt_nombre : {
                required : true,                
                minlength: 3
            },<?php echo PLTDC; ?>txt_alias : {
                required : true,
                regular: true,
                minlength: 3
            }              
        },              
        errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function(){
            plantillaDoc.postEditPlantillaDoc();
        }   
 });

    
        
</script>