<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-02-2015 02:02:08 
* Descripcion : formNewDepartamento.phtml
* ---------------------------------------
*/

/*prefijo: UBIG debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("UBIGGR");

$idPais = Aes::de(Formulario::getParam("_idPais")); 
?>
<form id="<?php echo UBIG; ?>formNewDepartamento" name="<?php echo UBIG; ?>formNewDepartamento" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo UBIG_07; ?></h4>
            </div>
            <div class="modal-body smart-form">                              
                <section>
                    <div class="row">
                       <label class="label col col-2"><?php echo UBIG_01; ?></label>
                        <div class="col col-10">
                            <label class="select"> 
                                <?php         
                                    $pais = departamentoController::listarPais();
                                    echo Functions::selectHtml(array(
                                        'data'=>$pais,
                                        'atributes'=>array(
                                            'id'=>UBIG.'lst_pais',
                                            'name'=>UBIG.'lst_pais'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>$idPais,  
                                        'encript'=> true,
                                        'enabled' => true,
                                        'txtSelect'=>false
                                    ));
                                ?><i></i>
                            </label>
                        </div>                         
                    </div>
                </section> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo UBIG_02; ?></label>
                        <div class="col col-10">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_descripcion" name="<?php echo UBIG; ?>txt_descripcion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_02M; ?></b>
                            </label>
                        </div>
                    </div>
                </section> 
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo UBIG; ?>btnGrDepartamento" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo UBIG; ?>formNewDepartamento");
</script>
<?php endif; ?>
<script>
$("#<?php echo UBIG; ?>formNewDepartamento").validate({
    rules : {
        <?php echo UBIG; ?>txt_descripcion : {
            required : true,                        
        }
    },   
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        departamento.postNewDepartamento();
    }   
});
</script>