<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 20-04-2016 16:04:52 
* Descripcion : formEditMetodoPago.phtml
* ---------------------------------------
*/

/*prefijo: MEPAG debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("MEPAGACT");
    
$data = metodoPagoController::findMetodoPago();

?>
<form id="<?php echo MEPAG; ?>formEditMetodoPago" name="<?php echo MEPAG; ?>formEditMetodoPago" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo MEPAG_03; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo MEPAG_04; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo MEPAG; ?>txt_nombre" name="<?php echo MEPAG; ?>txt_nombre" value="<?php echo $data['descripcion']; ?>"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo MEPAG_04M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>               
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo MEPAG_05; ?></label>
                        <div class="col col-6">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo MEPAG; ?>txt_icono" name="<?php echo MEPAG; ?>txt_icono" value="<?php echo $data['icono']; ?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo MEPAG_05M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo MEPAG_06; ?></label>
                        <div class="col col-4">
                            <label class="checkbox" >
                                <input type="checkbox" <?php echo ($data['sumar_caja'] == 'S')?'checked':'' ?>    
                                       name="<?php echo MEPAG; ?>chk_caja" id="<?php echo MEPAG; ?>chk_caja" value="S" />
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>                                                                                                                      
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo MEPAG; ?>btnEdMetodoPago" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo MEPAG; ?>formEditMetodoPago");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo MEPAG; ?>formEditMetodoPago").validate({
    rules : {
         <?php echo MEPAG; ?>txt_nombre : {
            required : true
        },
        <?php echo MEPAG; ?>txt_icono : {
            required : true
        }
    },
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        metodoPago.postEditMetodoPago();
    }   
});
</script>