<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 23-12-2014 14:12:17 
* Descripcion : formNewIdiomas.phtml
* ---------------------------------------
*/

/*prefijo: IDIOM debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("IDIOMGR");
?>
<form id="<?php echo IDIOM; ?>formNewIdiomas" name="<?php echo IDIOM; ?>formNewIdiomas" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo IDIOM_02; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
               <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo IDIOM_04; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo IDIOM; ?>txt_nombre" name="<?php echo IDIOM; ?>txt_nombre"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo IDIOM_04M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo IDIOM_08; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo IDIOM; ?>txt_nombreV" name="<?php echo IDIOM; ?>txt_nombreV"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo IDIOM_08M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo IDIOM_05; ?></label>
                        <div class="col col-6">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo IDIOM; ?>txt_abreviatura" name="<?php echo IDIOM; ?>txt_abreviatura"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo IDIOM_05M; ?></b>
                            </label>
                        </div>                        
                    </div>
                </section>
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo IDIOM_06; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo IDIOM; ?>txt_lang" name="<?php echo IDIOM; ?>txt_lang"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo IDIOM_06M; ?></b>
                            </label>
                        </div>                        
                    </div>
                </section>
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo IDIOM_07; ?></label>
                        <div class="col col-6">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo IDIOM; ?>txt_icono" name="<?php echo IDIOM; ?>txt_icono"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo IDIOM_07M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo IDIOM; ?>btnGrIdiomas" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo IDIOM; ?>formNewIdiomas");
</script>
<?php endif; ?>
<script>
$("#<?php echo IDIOM; ?>formNewIdiomas").validate({
    rules : {
        <?php echo IDIOM; ?>txt_nombre : {
            required : true,
            minlength: 2
        },
        <?php echo IDIOM; ?>txt_nombreV : {
            required : true,
            minlength: 2
        },
        <?php echo IDIOM; ?>txt_alias : {
            required : true
        }
    },
  
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        idiomas.postNewIdiomas();
    }   
});
</script>