<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-02-2015 02:02:08 
* Descripcion : formNewPais.phtml
* ---------------------------------------
*/

/*prefijo: UBIG debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("UBIGGR");
?>
<form id="<?php echo UBIG; ?>formNewPais" name="<?php echo UBIG; ?>formNewPais" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo UBIG_05; ?></h4>
            </div>
            <div class="modal-body smart-form">        
                <section>
                    <div class="row">
                       <label class="label col col-2"><?php echo UBIG_13; ?></label>
                        <div class="col col-10">
                            <label class="select"> 
                                <?php
                                    $continente = Array (
                                            Array ( 'id' => '01', 'descripcion' => 'África' ),
                                            Array ( 'id' => '02', 'descripcion' => 'Sur América' ),
                                            Array ( 'id' => '03', 'descripcion' => 'Europa Este' ),
                                            Array ( 'id' => '04', 'descripcion' => 'Asia' ),
                                            Array ( 'id' => '05', 'descripcion' => 'Oceanía' ),
                                            Array ( 'id' => '06', 'descripcion' => 'Antárctica' ),
                                            Array ( 'id' => '07', 'descripcion' => 'Europa Oeste' ),
                                            Array ( 'id' => '08', 'descripcion' => 'Norte América ' ),
                                            Array ( 'id' => '09', 'descripcion' => 'Centro América' ),
                                            Array ( 'id' => '10', 'descripcion' => 'Caribe' ),
                                            Array ( 'id' => '11', 'descripcion' => 'Medio Oriente' )
                                    );                                   
                                    echo Functions::selectHtml(array(
                                        'data'=>$continente,
                                        'atributes'=>array(
                                            'id'=>UBIG.'lst_continente',
                                            'name'=>UBIG.'lst_continente'
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>'02',
                                        'txtSelect'=>false
                                    ));
                                ?><i></i>
                            </label>
                        </div>                         
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo UBIG_01; ?></label>
                        <div class="col col-10">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_descripcion" name="<?php echo UBIG; ?>txt_descripcion">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_01M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo UBIG_23; ?></label>
                        <div class="col col-10">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_descripcion_es" name="<?php echo UBIG; ?>txt_descripcion_es">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_23M; ?></b>
                            </label>
                        </div>
                    </div>
                </section> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo UBIG_14; ?></label>
                        <div class="col col-4">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_aliasa2" name="<?php echo UBIG; ?>txt_aliasa2" maxlength="2">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_14M; ?></b>
                            </label>
                        </div>             
                        <label class="label col col-2"><?php echo UBIG_15; ?></label>
                        <div class="col col-4">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_aliasa3" name="<?php echo UBIG; ?>txt_aliasa3" maxlength="3">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_15M; ?></b>
                            </label>
                        </div>
                    </div>
                </section> 
                 <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo UBIG_16; ?></label>
                        <div class="col col-4">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_css" name="<?php echo UBIG; ?>txt_css">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_16M; ?></b>
                            </label>
                        </div>
                        <label class="label col col-2"><?php echo UBIG_18; ?></label>
                        <div class="col col-4">
                            <label class="input">
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo UBIG; ?>txt_codigoFono" name="<?php echo UBIG; ?>txt_codigoFono" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo UBIG_18M; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                       <label class="label col col-2"><?php echo LABEL_MONEDA; ?></label>
                        <div class="col col-4">
                            <label class="select"> 
                                <?php
                                    $moneda = monedaController::listarMoneda();                                   
                                    echo Functions::selectHtml(array(
                                        'data'=>$moneda,
                                        'atributes'=>array(
                                            'id'=>UBIG.'lst_moneda',
                                            'name'=>UBIG.'lst_moneda'                                           
                                        ),
                                        'etiqueta'=>'descripcion',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>false,
                                        'encript'=>true
                                    ));
                                ?>
                            </label>
                        </div>                                            
                        <label class="label col col-2"><?php echo GEAN_19; ?></label>
                        <div class="col col-4">
                           <label class="select"> 
                              <?php
                                  $idiomas = idiomasController::listarIdiomas();                                   
                                  echo Functions::selectHtml(array(
                                      'data'=>$idiomas,
                                      'atributes'=>array(
                                          'id'=>UBIG.'lst_idiomas',
                                          'name'=>UBIG.'lst_idiomas'                                           
                                      ),
                                      'etiqueta'=>'descripcion',
                                      'value'=>'id',
                                      'defaultEtiqueta'=>'',
                                      'txtSelect'=>false,
                                      'encript'=>true
                                  ));
                              ?>   
                              </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo UBIG; ?>btnGrPais" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo UBIG; ?>formNewPais");
</script>
<?php endif; ?>
<script>

  simpleScript.chosen({'id':'#<?php echo UBIG; ?>lst_moneda'});   
  simpleScript.chosen({'id':'#<?php echo UBIG; ?>lst_idiomas'});   
  
$("#<?php echo UBIG; ?>formNewPais").validate({
    rules : {
        <?php echo UBIG; ?>txt_descripcion : {
            required : true,                        
        }
    },   
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        pais.postNewPais();
    }   
});
</script>