<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 23-12-2014 14:12:17 
* Descripcion : indexIdiomas.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("IDIOMNEW");
$editar   = Session::getPermiso('IDIOMED');    
$file   = Session::getPermiso('IDIOMAJ');    

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>IDIOM,
        "title"=>IDIOM_01,
        'actions' => array(               
                array(
                    'id' => IDIOM . 'gridIdiomas_btnRecarga',                    
                    'permiso'=> 'IDIOMREC',
                    'click' => 'idiomas.getGridIdiomas();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo IDIOM; ?>btnNewIdiomas" type="button" onclick="idiomas.getFormNewIdiomas(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>                
            </div>
        </div>

    </div>
    
    <table id="<?php echo IDIOM; ?>gridIdiomas" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?> </button>                    
                    <?php endif;?>
                     <?php if($file["permiso"]): ?>
                        <button type="button" class="<?php echo $file['theme']; ?> margin-top-5" title="<?php echo $file['accion']; ?>" ><i class="<?php echo $file['icono'];?>"></i>  <?php echo $file['accion']; ?>   </button>                    
                    <?php endif;?>    
                        
                        
                </div>
            </div>

        </section>
    </div>
<?php echo Functions::widgetClose(); ?>