<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 12-09-2014 17:09:13 
* Descripcion : indexPlantillaDoc.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("PLTDCNEW");
$editar   = Session::getPermiso('PLTDCED');        
$clonar   = Session::getPermiso('PLTDCCL');
$anular   = Session::getPermiso('PLTDCDE');                

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>PLTDC,
        "title"=>PLTDC_01,
        'actions' => array(               
                array(
                    'id' => PLTDC . 'gridPlantillaDoc_btnRecarga',                    
                    'permiso'=> 'PLTDCREC',
                    'click' => 'plantillaDoc.getGridPlantillaDoc();'                    
                )
            )
    )); 
?>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo PLTDC; ?>btnNewPlantillaDoc" type="button" onclick="plantillaDoc.getFormNewPlantillaDoc();" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>                  
            </div>
        </div>

    </div>
    
    <table id="<?php echo PLTDC; ?>gridPlantillaDoc" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    
        <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?></button>                    
                    <?php endif;?>
                    <?php if($clonar["permiso"]): ?>
                    <button type="button" class="<?php echo $clonar['theme']; ?> margin-top-5" title="<?php echo $clonar['accion']; ?>" ><i class="<?php echo $clonar['icono'];?>"></i>  <?php echo $clonar['accion']; ?> </button>                    
                    <?php endif;?>
                    <?php if($anular["permiso"]): ?>
                        <button type="button" class="<?php echo $anular['theme']; ?> margin-top-5" title="<?php echo $anular['accion']; ?>" ><i class="<?php echo $anular['icono'];?>"></i>  <?php echo $anular['accion']; ?></button>                    
                    <?php endif;?>                    
                </div>
            </div>

        </section>
    </div>
    
<?php echo Functions::widgetClose(); ?>