<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 09-12-2014 17:12:42 
* Descripcion : indexMensajes.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("PMSJNEW");
$editar   = Session::getPermiso('PMSJED');
$clonar   = Session::getPermiso('PMSJCL');
$eliminar   = Session::getPermiso('PMSJDE');

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>PMSJ,
        "title"=>PMSJ_01,
        'actions' => array(               
                array(
                    'id' => PMSJ . 'gridMensajes_btnRecarga',                    
                    'permiso'=> 'PMSJREC',
                    'click' => 'mensajesPlantilla.getGridMensajes();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar">
        <div class="smart-form" style="position: absolute;left: 280px;top:5px;">         
            <div class="container">            
                <div class="row">
                        <label class="label col col-xs-1 text-align-right"><?php echo LABEL_IDIOMA; ?></label>        
                        <label class="input col col-xs-3">
                            <label class="select">
                                <?php
                                    $datax = idiomasController::listarIdiomas(); 
                                     echo Functions::selectHtml(array(
                                         'data'=>$datax,
                                         'atributes'=>array(
                                             'id'=>PMSJ.'lst_idioma',
                                             'name'=>PMSJ.'lst_idioma',
                                             'onchange' => 'mensajesPlantilla.getGridMensajes();'
                                         ),
                                         'etiqueta'=>'descripcion',
                                         'value'=>'id',
                                         'defaultEtiqueta'=>1,
                                         'encript'=> true,
                                         'txtSelect'=>false,
                                         'txtAll'=>true
                                     ));
                                 ?>
                            </label>
                        </label>                                   
                </div>            
            </div>                             
        </div>  
    </div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo PMSJ; ?>btnNewMensajes" type="button" onclick="mensajesPlantilla.getFormNewMensajes(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>                  
            </div>
        </div>

    </div>
    
    <table id="<?php echo PMSJ; ?>gridMensajes" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?> </button>                    
                    <?php endif;?>
                    <?php if($clonar["permiso"]): ?>
                        <button type="button" class="<?php echo $clonar['theme']; ?> margin-top-5" title="<?php echo $clonar['accion']; ?>" ><i class="<?php echo $clonar['icono'];?>"></i>  <?php echo $clonar['accion']; ?> </button>                    
                    <?php endif;?>
                    <?php if($eliminar["permiso"]): ?>
                        <button type="button" class="<?php echo $eliminar['theme']; ?> margin-top-5" title="<?php echo $eliminar['accion']; ?>" ><i class="<?php echo $eliminar['icono'];?>"></i>  <?php echo $eliminar['accion']; ?> </button>                    
                    <?php endif;?>
                </div>
            </div>

        </section>
    </div>      
<?php echo Functions::widgetClose(); ?>
<script>        
     simpleScript.chosen({'id':'#<?php echo PMSJ; ?>lst_idioma'});   
</script>