<?php 
$nuevo = Session::getPermiso('PARMNEW');
$editar = Session::getPermiso('PARMED');

echo Functions::siteMap();
echo Functions::widgetOpen(array(
        'id'=>T100,
        'title'=>LABEL_A1,
        'actions' => array(               
                array(
                    'id' => T100 . 'gridParametro_btnRecarga',                    
                    'permiso'=> 'PARMREC',
                    'click' => 'parametro.getGridParametro();'                    
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($nuevo['permiso']): ?>
                <button id="<?php echo T100; ?>btnNew" type="button" onclick="parametro.getNuevoParametro(this);" class="<?php echo $nuevo['theme']; ?>">
                    <i class="<?php echo $nuevo['icono']; ?>"></i> <?php echo $nuevo['accion']; ?>
                </button>
                <?php endif; ?>                 
            </div>
        </div>

    </div>
    
    <table id="<?php echo T100; ?>gridParametro" class="table table-striped table-hover table-condensed" style="width:100%"></table>
    
    <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?>  </button>                    
                    <?php endif;?>
                </div>
            </div>

        </section>
    </div>     
        
<?php echo Functions::widgetClose(); ?>