<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 17-12-2014 00:12:57 
* Descripcion : indexUbigeo.phtml
* ---------------------------------------
*/
$editar   = Session::getPermiso('UBIGED');
$eliminar = Session::getPermiso('UBIGDE');
$consultar = Session::getPermiso('UBIGCC');

echo Functions::siteMap();
?>
<article class="col-lg-12">
    <!--INICIO PAIS-->
<?php 
    $obj = array(
        'id'=>UBIG.'pais',
        'title'=>UBIG_19,
        'height'=>'260px',        
        'overflow'=>'none',
        'actions'=>array(
            array(
                'id'=>UBIG.'btnNewPais',
                'label'=>BTN_NUEVO,
                'click'=>'pais.getFormNewPais();'
            ),        
            array(
                'id' => UBIG . 'gridPais_btnRecarga',                    
                'permiso'=> 'UBIGREC',
                'click' => 'ubigeo.getGridPais();'                    
            )
                                            
        )
    );
    echo Functions::widgetOpen($obj);     
?>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">                
        <div class="dt-top-row">
            <div class="DTTT btn-group">                                       
            </div>
        </div>        
    </div>
    <table id="<?php echo UBIG; ?>gridPais" class="table table-striped table-hover table-condensed" style="width:95%"></table>
    
<?php echo Functions::widgetClose(); ?>
    <!--FIN DE PAIS-->
</article> 
<!--INICIO DE DEPARTAMENTO-->
<article class="col-lg-6">    
<?php
    $obj = array(
        'id'=>UBIG.'departamento',
        'title'=>UBIG_20,
        'height'=>'260px',        
        'overflow'=>'none',
        'actions'=>array(
            array(
                'id'=>UBIG.'btnNewDepartamento',
                'label'=>BTN_NUEVO,
                'click'=>'departamento.getFormNewDepartamento(ubigeo.getIdPais());'
            ),        
            array(
                'id' => UBIG . 'gridDepartamento_btnRecarga',                    
                'permiso'=> 'UBIGREC',
                'click' => 'ubigeo.getGridDepartamento();'                    
            )
        )
    );
    echo Functions::widgetOpen($obj); 

?>
    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">       
         <div class="dt-top-row" >           
            <div class="DTTT btn-group">                  
            </div>
        </div>
    </div>
    <table id="<?php echo UBIG; ?>gridDepartamento" class="table table-striped table-hover table-condensed" style="width:95%"></table>
    
    
  <?php echo Functions::widgetClose(); ?>
    
 <!--FIN DEPARTAMENTO-->
</article>

<!--INICIO DISTRITO / UBIGEO -->
<article class="col-lg-6">    
<?php
    $obj = array(
        'id'=>UBIG.'ubigeo',
        'title'=>UBIG_22,
        'height'=>'260px',        
        'overflow'=>'none',
        'actions'=>array(
            'nuevo'=>array(
                'id'=>UBIG.'btnNewUbigeo',
                'label'=>BTN_NUEVO,
                'click'=>'ubigeo.getFormNewUbigeo();'
            ),        
            array(
                'id' => UBIG . 'gridUbigeo_btnRecarga',                    
                'permiso'=> 'UBIGREC',
                'click' => 'ubigeo.getGridUbigeo();'                    
            )
        )
    );
    echo Functions::widgetOpen($obj); 

?>
  <div class="widget-body-toolbar"></div>
   <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
           <div class="dt-top-row" >            
            <div class="DTTT btn-group">                                  
            </div>
        </div>
    </div>
    <table id="<?php echo UBIG; ?>gridUbigeo" class="table table-striped table-hover table-condensed" style="width:95%"></table>
<?php  echo Functions::widgetClose(); ?>
    <!--FIN DISTRITO / UBIGEO -->
</article>
<div class="clearfix">
<article class="col-lg-12">  
    <div class="modal-body smart-form "> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($consultar["permiso"]): ?>
                        <button type="button" class="<?php echo $consultar['theme']; ?> margin-top-5" title="<?php echo $consultar['accion']; ?>" ><i class="<?php echo $consultar['icono'];?>"></i>  <?php echo $consultar['accion']; ?> </button>                    
                    <?php endif;?>
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar['theme']; ?> margin-top-5" title="<?php echo $editar['accion']; ?>" ><i class="<?php echo $editar['icono'];?>"></i>  <?php echo $editar['accion']; ?></button>                    
                    <?php endif;?>
                    <?php if($eliminar["permiso"]): ?>
                        <button type="button" class="<?php echo $eliminar['theme']; ?> margin-top-5" title="<?php echo $eliminar['accion']; ?>" ><i class="<?php echo $eliminar['icono'];?>"></i>  <?php echo $eliminar['accion']; ?> </button>                                        
                    <?php endif;?>
                </div>
            </div>

        </section>
    </div>     
</article>
</div>