<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 08-06-2016 02:06:12 
* Descripcion : formEditMProveedor.phtml
* ---------------------------------------
*/

/*prefijo: PROVV debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("PROVVACT");
    
$data = mProveedorController::findMProveedor();

?>
<form id="<?php echo PROVV; ?>formEditMProveedor" name="<?php echo PROVV; ?>formEditMProveedor" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">TITULO DE FORMULARIO</h4>
            </div>
            <div class="modal-body smart-form"> 
                CONTENIDO DEL FORM (utilizar constantes en Labels.php)
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo PROVV; ?>btnEdMProveedor" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo PROVV; ?>formEditMProveedor");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo PROVV; ?>formEditMProveedor").validate({
    rules : {
        <?php echo PROVV; ?>txt_campo : {
            required : true,
            regular: true,
            minlength: 3
        }
    },

    messages : {
        <?php echo PROVV; ?>txt_campo : {
            required : "Campo requerido",
            regular: "No se permite caracteres inválidos"
        }
    },

    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        mProveedor.postEditMProveedor();
    }   
});
</script>