<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 31-05-2016 00:05:51 
* Descripcion : formNewMClasificacion.phtml
* ---------------------------------------
*/

/*prefijo: CLASF debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("CLASFGR");
?>
<form id="<?php echo CLASF; ?>formNewMClasificacion" name="<?php echo CLASF; ?>formNewMClasificacion" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CLASF_02; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo CLASF_04; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo CLASF; ?>txt_descripcion" name="<?php echo CLASF; ?>txt_descripcion"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo CLASF_04M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>
                <section >
                    <div class="row">
                        <label class="label col col-2"><?php echo CLASF_05; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo CLASF; ?>txt_descripcion" name="<?php echo CLASF; ?>txt_descripcionCorta"  >
                                <b class="tooltip tooltip-top-right"><i class="fa  fa-question-circle txt-color-teal"></i> <?php echo CLASF_05M; ?></b>
                            </label>
                        </div>                       
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo CLASF; ?>btnGrMClasificacion" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CLASF; ?>formNewMClasificacion");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo CLASF; ?>formNewMClasificacion").validate({
    rules : {         
        <?php echo CLASF; ?>txt_descripcion : {
            required : true,            
            minlength: 2
        }, <?php echo CLASF; ?>txt_descripcionCorta : {
            required : true,
            minlength: 2
        }
    },
  
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        mClasificacion.postNewMClasificacion();
    }   
});
</script>