<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 31-05-2016 00:05:51 
* Descripcion : indexMClasificacion.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("CLASFNEW");
$editar    = Session::getPermiso("CLASFED");
$quitar    = Session::getPermiso("CLASFDE");
    
echo Functions::siteMap();
echo Functions::widgetOpen(array(
        "id"=>CLASF,
        "title"=>CLASF_01,
        "actions" => array(               
                array(
                    "id" => CLASF . "gridMClasificacion_btnRecarga",                    
                    "permiso"=> "CLASFREC",
                    "click" => "mClasificacion.getGridMClasificacion();"                  
                )
            )
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <!-- verificar permisos -->
                <?php if($nuevo["permiso"]): ?>
                <button id="<?php echo CLASF; ?>btnNewMClasificacion" type="button" onclick="mClasificacion.getFormNewMClasificacion(this);" class="<?php echo $nuevo["theme"]; ?>">
                    <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                </button>
                <?php endif; ?>                  
            </div>
        </div>

    </div>    
    <table id="<?php echo CLASF; ?>gridMClasificacion" class="table table-striped table-hover table-condensed" style="width:100%"></table>    
        
 <div class="modal-body smart-form"> 
        <section>
            <div class="row">
                <label class="label col col-1">
                <?php echo LABEL_LEYENDA; ?>
                </label>
                <div class="col col-10 ">
                    <?php if($editar["permiso"]): ?>
                        <button type="button" class="<?php echo $editar["theme"]; ?> margin-top-5" title="<?php echo $editar["accion"]; ?>" ><i class="<?php echo $editar["icono"];?>"></i>  <?php echo $editar["accion"]; ?> </button>                    
                    <?php endif;?>                                         
                    <?php if($quitar["permiso"]): ?>
                        <button type="button" class="<?php echo $quitar["theme"]; ?> margin-top-5" title="<?php echo $quitar["accion"]; ?>" ><i class="<?php echo $quitar["icono"];?>"></i>  <?php echo $quitar["accion"]; ?> </button>                    
                    <?php endif;?>       
                </div>
            </div>

        </section>
    </div>

<?php echo Functions::widgetClose(); ?>